// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import (
	"time"
)

const TableNameTKline5M = "t_kline_5m"

// TKline5M mapped from table <t_kline_5m>
type TKline5M struct {
	Ts      time.Time `gorm:"column:ts;type:timestamp without time zone;not null" json:"ts"`
	PoolID  int64     `gorm:"column:pool_id;type:bigint;not null" json:"pool_id,string"`
	Open    float64   `gorm:"column:open;type:double precision;not null" json:"open"`
	High    float64   `gorm:"column:high;type:double precision;not null" json:"high"`
	Low     float64   `gorm:"column:low;type:double precision;not null" json:"low"`
	Close   float64   `gorm:"column:close;type:double precision;not null" json:"close"`
	Volume0 float64   `gorm:"column:volume0;type:double precision;not null" json:"volume0"`
	Volume1 float64   `gorm:"column:volume1;type:double precision;not null" json:"volume1"`
	Volume  float64   `gorm:"column:volume;type:double precision;not null" json:"volume"`
}

// TableName TKline5M's table name
func (*TKline5M) TableName() string {
	return TableNameTKline5M
}
