// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import (
	"time"
)

const TableNameTKline1W = "t_kline_1w"

// TKline1W mapped from table <t_kline_1w>
type TKline1W struct {
	Ts      time.Time `gorm:"column:ts;type:timestamp without time zone" json:"ts"`
	PoolID  int64     `gorm:"column:pool_id;type:bigint" json:"pool_id,string"`
	Open    float64   `gorm:"column:open;type:double precision" json:"open"`
	High    float64   `gorm:"column:high;type:double precision" json:"high"`
	Low     float64   `gorm:"column:low;type:double precision" json:"low"`
	Close   float64   `gorm:"column:close;type:double precision" json:"close"`
	Volume0 float64   `gorm:"column:volume0;type:double precision" json:"volume0"`
	Volume1 float64   `gorm:"column:volume1;type:double precision" json:"volume1"`
	Volume  float64   `gorm:"column:volume;type:double precision" json:"volume"`
}

// TableName TKline1W's table name
func (*TKline1W) TableName() string {
	return TableNameTKline1W
}
