// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import (
	"time"
)

const TableNameTLiquidityModify = "t_liquidity_modify"

// TLiquidityModify mapped from table <t_liquidity_modify>
type TLiquidityModify struct {
	Ts      time.Time `gorm:"column:ts;type:timestamp without time zone;not null" json:"ts"`
	PoolID  int64     `gorm:"column:pool_id;type:bigint;not null" json:"pool_id,string"`
	Amount0 float64   `gorm:"column:amount0;type:numeric(60,0);not null" json:"amount0"`
	Amount1 float64   `gorm:"column:amount1;type:numeric(60,0);not null" json:"amount1"`
	Amountu float64   `gorm:"column:amountu;type:double precision;not null" json:"amountu"`
}

// TableName TLiquidityModify's table name
func (*TLiquidityModify) TableName() string {
	return TableNameTLiquidityModify
}
