// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import (
	"time"
)

const TableNameTTrade = "t_trade"

// TTrade mapped from table <t_trade>
type TTrade struct {
	Ts      time.Time `gorm:"column:ts;type:timestamp without time zone;not null" json:"ts"`
	PoolID  int64     `gorm:"column:pool_id;type:bigint;not null" json:"pool_id,string"`
	IsBuy   bool      `gorm:"column:is_buy;type:boolean;not null" json:"is_buy"`
	Price   float64   `gorm:"column:price;type:double precision;not null" json:"price"`
	Price01 float64   `gorm:"column:price01;type:double precision;not null" json:"price01"`
	Amount0 float64   `gorm:"column:amount0;type:double precision;not null" json:"amount0"`
	Amount1 float64   `gorm:"column:amount1;type:double precision;not null" json:"amount1"`
	Amount  float64   `gorm:"column:amount;type:double precision;not null" json:"amount"`
}

// TableName TTrade's table name
func (*TTrade) TableName() string {
	return TableNameTTrade
}
