// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTDexPool(db *gorm.DB, opts ...gen.DOOption) tDexPool {
	_tDexPool := tDexPool{}

	_tDexPool.tDexPoolDo.UseDB(db, opts...)
	_tDexPool.tDexPoolDo.UseModel(&model.TDexPool{})

	tableName := _tDexPool.tDexPoolDo.TableName()
	_tDexPool.ALL = field.NewAsterisk(tableName)
	_tDexPool.ID = field.NewInt32(tableName, "id")
	_tDexPool.DexID = field.NewInt32(tableName, "dex_id")
	_tDexPool.Name = field.NewString(tableName, "name")
	_tDexPool.Version = field.NewString(tableName, "version")
	_tDexPool.Icon = field.NewString(tableName, "icon")
	_tDexPool.Website = field.NewString(tableName, "website")
	_tDexPool.CreatedAt = field.NewTime(tableName, "created_at")
	_tDexPool.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tDexPool.fillFieldMap()

	return _tDexPool
}

type tDexPool struct {
	tDexPoolDo tDexPoolDo

	ALL       field.Asterisk
	ID        field.Int32
	DexID     field.Int32
	Name      field.String
	Version   field.String
	Icon      field.String
	Website   field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t tDexPool) Table(newTableName string) *tDexPool {
	t.tDexPoolDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tDexPool) As(alias string) *tDexPool {
	t.tDexPoolDo.DO = *(t.tDexPoolDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tDexPool) updateTableName(table string) *tDexPool {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.DexID = field.NewInt32(table, "dex_id")
	t.Name = field.NewString(table, "name")
	t.Version = field.NewString(table, "version")
	t.Icon = field.NewString(table, "icon")
	t.Website = field.NewString(table, "website")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tDexPool) WithContext(ctx context.Context) ITDexPoolDo { return t.tDexPoolDo.WithContext(ctx) }

func (t tDexPool) TableName() string { return t.tDexPoolDo.TableName() }

func (t tDexPool) Alias() string { return t.tDexPoolDo.Alias() }

func (t tDexPool) Columns(cols ...field.Expr) gen.Columns { return t.tDexPoolDo.Columns(cols...) }

func (t *tDexPool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tDexPool) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["dex_id"] = t.DexID
	t.fieldMap["name"] = t.Name
	t.fieldMap["version"] = t.Version
	t.fieldMap["icon"] = t.Icon
	t.fieldMap["website"] = t.Website
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tDexPool) clone(db *gorm.DB) tDexPool {
	t.tDexPoolDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tDexPool) replaceDB(db *gorm.DB) tDexPool {
	t.tDexPoolDo.ReplaceDB(db)
	return t
}

type tDexPoolDo struct{ gen.DO }

type ITDexPoolDo interface {
	gen.SubQuery
	Debug() ITDexPoolDo
	WithContext(ctx context.Context) ITDexPoolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITDexPoolDo
	WriteDB() ITDexPoolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITDexPoolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITDexPoolDo
	Not(conds ...gen.Condition) ITDexPoolDo
	Or(conds ...gen.Condition) ITDexPoolDo
	Select(conds ...field.Expr) ITDexPoolDo
	Where(conds ...gen.Condition) ITDexPoolDo
	Order(conds ...field.Expr) ITDexPoolDo
	Distinct(cols ...field.Expr) ITDexPoolDo
	Omit(cols ...field.Expr) ITDexPoolDo
	Join(table schema.Tabler, on ...field.Expr) ITDexPoolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITDexPoolDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITDexPoolDo
	Group(cols ...field.Expr) ITDexPoolDo
	Having(conds ...gen.Condition) ITDexPoolDo
	Limit(limit int) ITDexPoolDo
	Offset(offset int) ITDexPoolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITDexPoolDo
	Unscoped() ITDexPoolDo
	Create(values ...*model.TDexPool) error
	CreateInBatches(values []*model.TDexPool, batchSize int) error
	Save(values ...*model.TDexPool) error
	First() (*model.TDexPool, error)
	Take() (*model.TDexPool, error)
	Last() (*model.TDexPool, error)
	Find() ([]*model.TDexPool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDexPool, err error)
	FindInBatches(result *[]*model.TDexPool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TDexPool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITDexPoolDo
	Assign(attrs ...field.AssignExpr) ITDexPoolDo
	Joins(fields ...field.RelationField) ITDexPoolDo
	Preload(fields ...field.RelationField) ITDexPoolDo
	FirstOrInit() (*model.TDexPool, error)
	FirstOrCreate() (*model.TDexPool, error)
	FindByPage(offset int, limit int) (result []*model.TDexPool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITDexPoolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tDexPoolDo) Debug() ITDexPoolDo {
	return t.withDO(t.DO.Debug())
}

func (t tDexPoolDo) WithContext(ctx context.Context) ITDexPoolDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tDexPoolDo) ReadDB() ITDexPoolDo {
	return t.Clauses(dbresolver.Read)
}

func (t tDexPoolDo) WriteDB() ITDexPoolDo {
	return t.Clauses(dbresolver.Write)
}

func (t tDexPoolDo) Session(config *gorm.Session) ITDexPoolDo {
	return t.withDO(t.DO.Session(config))
}

func (t tDexPoolDo) Clauses(conds ...clause.Expression) ITDexPoolDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tDexPoolDo) Returning(value interface{}, columns ...string) ITDexPoolDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tDexPoolDo) Not(conds ...gen.Condition) ITDexPoolDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tDexPoolDo) Or(conds ...gen.Condition) ITDexPoolDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tDexPoolDo) Select(conds ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tDexPoolDo) Where(conds ...gen.Condition) ITDexPoolDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tDexPoolDo) Order(conds ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tDexPoolDo) Distinct(cols ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tDexPoolDo) Omit(cols ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tDexPoolDo) Join(table schema.Tabler, on ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tDexPoolDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tDexPoolDo) RightJoin(table schema.Tabler, on ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tDexPoolDo) Group(cols ...field.Expr) ITDexPoolDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tDexPoolDo) Having(conds ...gen.Condition) ITDexPoolDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tDexPoolDo) Limit(limit int) ITDexPoolDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tDexPoolDo) Offset(offset int) ITDexPoolDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tDexPoolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITDexPoolDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tDexPoolDo) Unscoped() ITDexPoolDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tDexPoolDo) Create(values ...*model.TDexPool) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tDexPoolDo) CreateInBatches(values []*model.TDexPool, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tDexPoolDo) Save(values ...*model.TDexPool) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tDexPoolDo) First() (*model.TDexPool, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDexPool), nil
	}
}

func (t tDexPoolDo) Take() (*model.TDexPool, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDexPool), nil
	}
}

func (t tDexPoolDo) Last() (*model.TDexPool, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDexPool), nil
	}
}

func (t tDexPoolDo) Find() ([]*model.TDexPool, error) {
	result, err := t.DO.Find()
	return result.([]*model.TDexPool), err
}

func (t tDexPoolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDexPool, err error) {
	buf := make([]*model.TDexPool, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tDexPoolDo) FindInBatches(result *[]*model.TDexPool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tDexPoolDo) Attrs(attrs ...field.AssignExpr) ITDexPoolDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tDexPoolDo) Assign(attrs ...field.AssignExpr) ITDexPoolDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tDexPoolDo) Joins(fields ...field.RelationField) ITDexPoolDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tDexPoolDo) Preload(fields ...field.RelationField) ITDexPoolDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tDexPoolDo) FirstOrInit() (*model.TDexPool, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDexPool), nil
	}
}

func (t tDexPoolDo) FirstOrCreate() (*model.TDexPool, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDexPool), nil
	}
}

func (t tDexPoolDo) FindByPage(offset int, limit int) (result []*model.TDexPool, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tDexPoolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tDexPoolDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tDexPoolDo) Delete(models ...*model.TDexPool) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tDexPoolDo) withDO(do gen.Dao) *tDexPoolDo {
	t.DO = *do.(*gen.DO)
	return t
}
