// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTDex(db *gorm.DB, opts ...gen.DOOption) tDex {
	_tDex := tDex{}

	_tDex.tDexDo.UseDB(db, opts...)
	_tDex.tDexDo.UseModel(&model.TDex{})

	tableName := _tDex.tDexDo.TableName()
	_tDex.ALL = field.NewAsterisk(tableName)
	_tDex.ID = field.NewInt32(tableName, "id")
	_tDex.Name = field.NewString(tableName, "name")
	_tDex.Version = field.NewString(tableName, "version")
	_tDex.Icon = field.NewString(tableName, "icon")
	_tDex.Website = field.NewString(tableName, "website")
	_tDex.CreatedAt = field.NewTime(tableName, "created_at")
	_tDex.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tDex.fillFieldMap()

	return _tDex
}

type tDex struct {
	tDexDo tDexDo

	ALL       field.Asterisk
	ID        field.Int32
	Name      field.String
	Version   field.String
	Icon      field.String
	Website   field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t tDex) Table(newTableName string) *tDex {
	t.tDexDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tDex) As(alias string) *tDex {
	t.tDexDo.DO = *(t.tDexDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tDex) updateTableName(table string) *tDex {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.Name = field.NewString(table, "name")
	t.Version = field.NewString(table, "version")
	t.Icon = field.NewString(table, "icon")
	t.Website = field.NewString(table, "website")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tDex) WithContext(ctx context.Context) ITDexDo { return t.tDexDo.WithContext(ctx) }

func (t tDex) TableName() string { return t.tDexDo.TableName() }

func (t tDex) Alias() string { return t.tDexDo.Alias() }

func (t tDex) Columns(cols ...field.Expr) gen.Columns { return t.tDexDo.Columns(cols...) }

func (t *tDex) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tDex) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["version"] = t.Version
	t.fieldMap["icon"] = t.Icon
	t.fieldMap["website"] = t.Website
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tDex) clone(db *gorm.DB) tDex {
	t.tDexDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tDex) replaceDB(db *gorm.DB) tDex {
	t.tDexDo.ReplaceDB(db)
	return t
}

type tDexDo struct{ gen.DO }

type ITDexDo interface {
	gen.SubQuery
	Debug() ITDexDo
	WithContext(ctx context.Context) ITDexDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITDexDo
	WriteDB() ITDexDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITDexDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITDexDo
	Not(conds ...gen.Condition) ITDexDo
	Or(conds ...gen.Condition) ITDexDo
	Select(conds ...field.Expr) ITDexDo
	Where(conds ...gen.Condition) ITDexDo
	Order(conds ...field.Expr) ITDexDo
	Distinct(cols ...field.Expr) ITDexDo
	Omit(cols ...field.Expr) ITDexDo
	Join(table schema.Tabler, on ...field.Expr) ITDexDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITDexDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITDexDo
	Group(cols ...field.Expr) ITDexDo
	Having(conds ...gen.Condition) ITDexDo
	Limit(limit int) ITDexDo
	Offset(offset int) ITDexDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITDexDo
	Unscoped() ITDexDo
	Create(values ...*model.TDex) error
	CreateInBatches(values []*model.TDex, batchSize int) error
	Save(values ...*model.TDex) error
	First() (*model.TDex, error)
	Take() (*model.TDex, error)
	Last() (*model.TDex, error)
	Find() ([]*model.TDex, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDex, err error)
	FindInBatches(result *[]*model.TDex, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TDex) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITDexDo
	Assign(attrs ...field.AssignExpr) ITDexDo
	Joins(fields ...field.RelationField) ITDexDo
	Preload(fields ...field.RelationField) ITDexDo
	FirstOrInit() (*model.TDex, error)
	FirstOrCreate() (*model.TDex, error)
	FindByPage(offset int, limit int) (result []*model.TDex, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITDexDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tDexDo) Debug() ITDexDo {
	return t.withDO(t.DO.Debug())
}

func (t tDexDo) WithContext(ctx context.Context) ITDexDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tDexDo) ReadDB() ITDexDo {
	return t.Clauses(dbresolver.Read)
}

func (t tDexDo) WriteDB() ITDexDo {
	return t.Clauses(dbresolver.Write)
}

func (t tDexDo) Session(config *gorm.Session) ITDexDo {
	return t.withDO(t.DO.Session(config))
}

func (t tDexDo) Clauses(conds ...clause.Expression) ITDexDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tDexDo) Returning(value interface{}, columns ...string) ITDexDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tDexDo) Not(conds ...gen.Condition) ITDexDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tDexDo) Or(conds ...gen.Condition) ITDexDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tDexDo) Select(conds ...field.Expr) ITDexDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tDexDo) Where(conds ...gen.Condition) ITDexDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tDexDo) Order(conds ...field.Expr) ITDexDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tDexDo) Distinct(cols ...field.Expr) ITDexDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tDexDo) Omit(cols ...field.Expr) ITDexDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tDexDo) Join(table schema.Tabler, on ...field.Expr) ITDexDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tDexDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITDexDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tDexDo) RightJoin(table schema.Tabler, on ...field.Expr) ITDexDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tDexDo) Group(cols ...field.Expr) ITDexDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tDexDo) Having(conds ...gen.Condition) ITDexDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tDexDo) Limit(limit int) ITDexDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tDexDo) Offset(offset int) ITDexDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tDexDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITDexDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tDexDo) Unscoped() ITDexDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tDexDo) Create(values ...*model.TDex) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tDexDo) CreateInBatches(values []*model.TDex, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tDexDo) Save(values ...*model.TDex) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tDexDo) First() (*model.TDex, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDex), nil
	}
}

func (t tDexDo) Take() (*model.TDex, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDex), nil
	}
}

func (t tDexDo) Last() (*model.TDex, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDex), nil
	}
}

func (t tDexDo) Find() ([]*model.TDex, error) {
	result, err := t.DO.Find()
	return result.([]*model.TDex), err
}

func (t tDexDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDex, err error) {
	buf := make([]*model.TDex, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tDexDo) FindInBatches(result *[]*model.TDex, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tDexDo) Attrs(attrs ...field.AssignExpr) ITDexDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tDexDo) Assign(attrs ...field.AssignExpr) ITDexDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tDexDo) Joins(fields ...field.RelationField) ITDexDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tDexDo) Preload(fields ...field.RelationField) ITDexDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tDexDo) FirstOrInit() (*model.TDex, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDex), nil
	}
}

func (t tDexDo) FirstOrCreate() (*model.TDex, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDex), nil
	}
}

func (t tDexDo) FindByPage(offset int, limit int) (result []*model.TDex, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tDexDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tDexDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tDexDo) Delete(models ...*model.TDex) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tDexDo) withDO(do gen.Dao) *tDexDo {
	t.DO = *do.(*gen.DO)
	return t
}
