// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTFamousToken(db *gorm.DB, opts ...gen.DOOption) tFamousToken {
	_tFamousToken := tFamousToken{}

	_tFamousToken.tFamousTokenDo.UseDB(db, opts...)
	_tFamousToken.tFamousTokenDo.UseModel(&model.TFamousToken{})

	tableName := _tFamousToken.tFamousTokenDo.TableName()
	_tFamousToken.ALL = field.NewAsterisk(tableName)
	_tFamousToken.ID = field.NewInt32(tableName, "id")
	_tFamousToken.TokenName = field.NewString(tableName, "token_name")
	_tFamousToken.ChainName = field.NewString(tableName, "chain_name")
	_tFamousToken.TokenAddress = field.NewString(tableName, "token_address")
	_tFamousToken.Decimals = field.NewInt32(tableName, "decimals")
	_tFamousToken.IsStable = field.NewBool(tableName, "is_stable")
	_tFamousToken.IsNative = field.NewBool(tableName, "is_native")
	_tFamousToken.FullName = field.NewString(tableName, "full_name")
	_tFamousToken.TotalSupply = field.NewField(tableName, "total_supply")
	_tFamousToken.Icon = field.NewString(tableName, "icon")
	_tFamousToken.Flags = field.NewInt32(tableName, "flags")
	_tFamousToken.CreatedAt = field.NewTime(tableName, "created_at")
	_tFamousToken.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tFamousToken.fillFieldMap()

	return _tFamousToken
}

type tFamousToken struct {
	tFamousTokenDo tFamousTokenDo

	ALL          field.Asterisk
	ID           field.Int32
	TokenName    field.String
	ChainName    field.String
	TokenAddress field.String
	Decimals     field.Int32
	IsStable     field.Bool
	IsNative     field.Bool
	FullName     field.String
	TotalSupply  field.Field
	Icon         field.String
	Flags        field.Int32
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t tFamousToken) Table(newTableName string) *tFamousToken {
	t.tFamousTokenDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tFamousToken) As(alias string) *tFamousToken {
	t.tFamousTokenDo.DO = *(t.tFamousTokenDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tFamousToken) updateTableName(table string) *tFamousToken {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.TokenName = field.NewString(table, "token_name")
	t.ChainName = field.NewString(table, "chain_name")
	t.TokenAddress = field.NewString(table, "token_address")
	t.Decimals = field.NewInt32(table, "decimals")
	t.IsStable = field.NewBool(table, "is_stable")
	t.IsNative = field.NewBool(table, "is_native")
	t.FullName = field.NewString(table, "full_name")
	t.TotalSupply = field.NewField(table, "total_supply")
	t.Icon = field.NewString(table, "icon")
	t.Flags = field.NewInt32(table, "flags")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tFamousToken) WithContext(ctx context.Context) ITFamousTokenDo {
	return t.tFamousTokenDo.WithContext(ctx)
}

func (t tFamousToken) TableName() string { return t.tFamousTokenDo.TableName() }

func (t tFamousToken) Alias() string { return t.tFamousTokenDo.Alias() }

func (t tFamousToken) Columns(cols ...field.Expr) gen.Columns {
	return t.tFamousTokenDo.Columns(cols...)
}

func (t *tFamousToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tFamousToken) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["token_name"] = t.TokenName
	t.fieldMap["chain_name"] = t.ChainName
	t.fieldMap["token_address"] = t.TokenAddress
	t.fieldMap["decimals"] = t.Decimals
	t.fieldMap["is_stable"] = t.IsStable
	t.fieldMap["is_native"] = t.IsNative
	t.fieldMap["full_name"] = t.FullName
	t.fieldMap["total_supply"] = t.TotalSupply
	t.fieldMap["icon"] = t.Icon
	t.fieldMap["flags"] = t.Flags
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tFamousToken) clone(db *gorm.DB) tFamousToken {
	t.tFamousTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tFamousToken) replaceDB(db *gorm.DB) tFamousToken {
	t.tFamousTokenDo.ReplaceDB(db)
	return t
}

type tFamousTokenDo struct{ gen.DO }

type ITFamousTokenDo interface {
	gen.SubQuery
	Debug() ITFamousTokenDo
	WithContext(ctx context.Context) ITFamousTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITFamousTokenDo
	WriteDB() ITFamousTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITFamousTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITFamousTokenDo
	Not(conds ...gen.Condition) ITFamousTokenDo
	Or(conds ...gen.Condition) ITFamousTokenDo
	Select(conds ...field.Expr) ITFamousTokenDo
	Where(conds ...gen.Condition) ITFamousTokenDo
	Order(conds ...field.Expr) ITFamousTokenDo
	Distinct(cols ...field.Expr) ITFamousTokenDo
	Omit(cols ...field.Expr) ITFamousTokenDo
	Join(table schema.Tabler, on ...field.Expr) ITFamousTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITFamousTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITFamousTokenDo
	Group(cols ...field.Expr) ITFamousTokenDo
	Having(conds ...gen.Condition) ITFamousTokenDo
	Limit(limit int) ITFamousTokenDo
	Offset(offset int) ITFamousTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITFamousTokenDo
	Unscoped() ITFamousTokenDo
	Create(values ...*model.TFamousToken) error
	CreateInBatches(values []*model.TFamousToken, batchSize int) error
	Save(values ...*model.TFamousToken) error
	First() (*model.TFamousToken, error)
	Take() (*model.TFamousToken, error)
	Last() (*model.TFamousToken, error)
	Find() ([]*model.TFamousToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TFamousToken, err error)
	FindInBatches(result *[]*model.TFamousToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TFamousToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITFamousTokenDo
	Assign(attrs ...field.AssignExpr) ITFamousTokenDo
	Joins(fields ...field.RelationField) ITFamousTokenDo
	Preload(fields ...field.RelationField) ITFamousTokenDo
	FirstOrInit() (*model.TFamousToken, error)
	FirstOrCreate() (*model.TFamousToken, error)
	FindByPage(offset int, limit int) (result []*model.TFamousToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITFamousTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tFamousTokenDo) Debug() ITFamousTokenDo {
	return t.withDO(t.DO.Debug())
}

func (t tFamousTokenDo) WithContext(ctx context.Context) ITFamousTokenDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tFamousTokenDo) ReadDB() ITFamousTokenDo {
	return t.Clauses(dbresolver.Read)
}

func (t tFamousTokenDo) WriteDB() ITFamousTokenDo {
	return t.Clauses(dbresolver.Write)
}

func (t tFamousTokenDo) Session(config *gorm.Session) ITFamousTokenDo {
	return t.withDO(t.DO.Session(config))
}

func (t tFamousTokenDo) Clauses(conds ...clause.Expression) ITFamousTokenDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tFamousTokenDo) Returning(value interface{}, columns ...string) ITFamousTokenDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tFamousTokenDo) Not(conds ...gen.Condition) ITFamousTokenDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tFamousTokenDo) Or(conds ...gen.Condition) ITFamousTokenDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tFamousTokenDo) Select(conds ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tFamousTokenDo) Where(conds ...gen.Condition) ITFamousTokenDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tFamousTokenDo) Order(conds ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tFamousTokenDo) Distinct(cols ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tFamousTokenDo) Omit(cols ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tFamousTokenDo) Join(table schema.Tabler, on ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tFamousTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tFamousTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tFamousTokenDo) Group(cols ...field.Expr) ITFamousTokenDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tFamousTokenDo) Having(conds ...gen.Condition) ITFamousTokenDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tFamousTokenDo) Limit(limit int) ITFamousTokenDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tFamousTokenDo) Offset(offset int) ITFamousTokenDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tFamousTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITFamousTokenDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tFamousTokenDo) Unscoped() ITFamousTokenDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tFamousTokenDo) Create(values ...*model.TFamousToken) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tFamousTokenDo) CreateInBatches(values []*model.TFamousToken, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tFamousTokenDo) Save(values ...*model.TFamousToken) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tFamousTokenDo) First() (*model.TFamousToken, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TFamousToken), nil
	}
}

func (t tFamousTokenDo) Take() (*model.TFamousToken, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TFamousToken), nil
	}
}

func (t tFamousTokenDo) Last() (*model.TFamousToken, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TFamousToken), nil
	}
}

func (t tFamousTokenDo) Find() ([]*model.TFamousToken, error) {
	result, err := t.DO.Find()
	return result.([]*model.TFamousToken), err
}

func (t tFamousTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TFamousToken, err error) {
	buf := make([]*model.TFamousToken, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tFamousTokenDo) FindInBatches(result *[]*model.TFamousToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tFamousTokenDo) Attrs(attrs ...field.AssignExpr) ITFamousTokenDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tFamousTokenDo) Assign(attrs ...field.AssignExpr) ITFamousTokenDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tFamousTokenDo) Joins(fields ...field.RelationField) ITFamousTokenDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tFamousTokenDo) Preload(fields ...field.RelationField) ITFamousTokenDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tFamousTokenDo) FirstOrInit() (*model.TFamousToken, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TFamousToken), nil
	}
}

func (t tFamousTokenDo) FirstOrCreate() (*model.TFamousToken, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TFamousToken), nil
	}
}

func (t tFamousTokenDo) FindByPage(offset int, limit int) (result []*model.TFamousToken, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tFamousTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tFamousTokenDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tFamousTokenDo) Delete(models ...*model.TFamousToken) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tFamousTokenDo) withDO(do gen.Dao) *tFamousTokenDo {
	t.DO = *do.(*gen.DO)
	return t
}
