// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTLaunchpad(db *gorm.DB, opts ...gen.DOOption) tLaunchpad {
	_tLaunchpad := tLaunchpad{}

	_tLaunchpad.tLaunchpadDo.UseDB(db, opts...)
	_tLaunchpad.tLaunchpadDo.UseModel(&model.TLaunchpad{})

	tableName := _tLaunchpad.tLaunchpadDo.TableName()
	_tLaunchpad.ALL = field.NewAsterisk(tableName)
	_tLaunchpad.ID = field.NewInt32(tableName, "id")
	_tLaunchpad.Name = field.NewString(tableName, "name")
	_tLaunchpad.Version = field.NewString(tableName, "version")
	_tLaunchpad.Factory = field.NewString(tableName, "factory")
	_tLaunchpad.Icon = field.NewString(tableName, "icon")
	_tLaunchpad.Website = field.NewString(tableName, "website")
	_tLaunchpad.CreatedAt = field.NewTime(tableName, "created_at")
	_tLaunchpad.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tLaunchpad.fillFieldMap()

	return _tLaunchpad
}

type tLaunchpad struct {
	tLaunchpadDo tLaunchpadDo

	ALL       field.Asterisk
	ID        field.Int32
	Name      field.String
	Version   field.String
	Factory   field.String
	Icon      field.String
	Website   field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t tLaunchpad) Table(newTableName string) *tLaunchpad {
	t.tLaunchpadDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tLaunchpad) As(alias string) *tLaunchpad {
	t.tLaunchpadDo.DO = *(t.tLaunchpadDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tLaunchpad) updateTableName(table string) *tLaunchpad {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.Name = field.NewString(table, "name")
	t.Version = field.NewString(table, "version")
	t.Factory = field.NewString(table, "factory")
	t.Icon = field.NewString(table, "icon")
	t.Website = field.NewString(table, "website")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tLaunchpad) WithContext(ctx context.Context) ITLaunchpadDo {
	return t.tLaunchpadDo.WithContext(ctx)
}

func (t tLaunchpad) TableName() string { return t.tLaunchpadDo.TableName() }

func (t tLaunchpad) Alias() string { return t.tLaunchpadDo.Alias() }

func (t tLaunchpad) Columns(cols ...field.Expr) gen.Columns { return t.tLaunchpadDo.Columns(cols...) }

func (t *tLaunchpad) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tLaunchpad) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["version"] = t.Version
	t.fieldMap["factory"] = t.Factory
	t.fieldMap["icon"] = t.Icon
	t.fieldMap["website"] = t.Website
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tLaunchpad) clone(db *gorm.DB) tLaunchpad {
	t.tLaunchpadDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tLaunchpad) replaceDB(db *gorm.DB) tLaunchpad {
	t.tLaunchpadDo.ReplaceDB(db)
	return t
}

type tLaunchpadDo struct{ gen.DO }

type ITLaunchpadDo interface {
	gen.SubQuery
	Debug() ITLaunchpadDo
	WithContext(ctx context.Context) ITLaunchpadDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITLaunchpadDo
	WriteDB() ITLaunchpadDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITLaunchpadDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITLaunchpadDo
	Not(conds ...gen.Condition) ITLaunchpadDo
	Or(conds ...gen.Condition) ITLaunchpadDo
	Select(conds ...field.Expr) ITLaunchpadDo
	Where(conds ...gen.Condition) ITLaunchpadDo
	Order(conds ...field.Expr) ITLaunchpadDo
	Distinct(cols ...field.Expr) ITLaunchpadDo
	Omit(cols ...field.Expr) ITLaunchpadDo
	Join(table schema.Tabler, on ...field.Expr) ITLaunchpadDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITLaunchpadDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITLaunchpadDo
	Group(cols ...field.Expr) ITLaunchpadDo
	Having(conds ...gen.Condition) ITLaunchpadDo
	Limit(limit int) ITLaunchpadDo
	Offset(offset int) ITLaunchpadDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITLaunchpadDo
	Unscoped() ITLaunchpadDo
	Create(values ...*model.TLaunchpad) error
	CreateInBatches(values []*model.TLaunchpad, batchSize int) error
	Save(values ...*model.TLaunchpad) error
	First() (*model.TLaunchpad, error)
	Take() (*model.TLaunchpad, error)
	Last() (*model.TLaunchpad, error)
	Find() ([]*model.TLaunchpad, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TLaunchpad, err error)
	FindInBatches(result *[]*model.TLaunchpad, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TLaunchpad) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITLaunchpadDo
	Assign(attrs ...field.AssignExpr) ITLaunchpadDo
	Joins(fields ...field.RelationField) ITLaunchpadDo
	Preload(fields ...field.RelationField) ITLaunchpadDo
	FirstOrInit() (*model.TLaunchpad, error)
	FirstOrCreate() (*model.TLaunchpad, error)
	FindByPage(offset int, limit int) (result []*model.TLaunchpad, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITLaunchpadDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tLaunchpadDo) Debug() ITLaunchpadDo {
	return t.withDO(t.DO.Debug())
}

func (t tLaunchpadDo) WithContext(ctx context.Context) ITLaunchpadDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tLaunchpadDo) ReadDB() ITLaunchpadDo {
	return t.Clauses(dbresolver.Read)
}

func (t tLaunchpadDo) WriteDB() ITLaunchpadDo {
	return t.Clauses(dbresolver.Write)
}

func (t tLaunchpadDo) Session(config *gorm.Session) ITLaunchpadDo {
	return t.withDO(t.DO.Session(config))
}

func (t tLaunchpadDo) Clauses(conds ...clause.Expression) ITLaunchpadDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tLaunchpadDo) Returning(value interface{}, columns ...string) ITLaunchpadDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tLaunchpadDo) Not(conds ...gen.Condition) ITLaunchpadDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tLaunchpadDo) Or(conds ...gen.Condition) ITLaunchpadDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tLaunchpadDo) Select(conds ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tLaunchpadDo) Where(conds ...gen.Condition) ITLaunchpadDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tLaunchpadDo) Order(conds ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tLaunchpadDo) Distinct(cols ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tLaunchpadDo) Omit(cols ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tLaunchpadDo) Join(table schema.Tabler, on ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tLaunchpadDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tLaunchpadDo) RightJoin(table schema.Tabler, on ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tLaunchpadDo) Group(cols ...field.Expr) ITLaunchpadDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tLaunchpadDo) Having(conds ...gen.Condition) ITLaunchpadDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tLaunchpadDo) Limit(limit int) ITLaunchpadDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tLaunchpadDo) Offset(offset int) ITLaunchpadDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tLaunchpadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITLaunchpadDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tLaunchpadDo) Unscoped() ITLaunchpadDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tLaunchpadDo) Create(values ...*model.TLaunchpad) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tLaunchpadDo) CreateInBatches(values []*model.TLaunchpad, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tLaunchpadDo) Save(values ...*model.TLaunchpad) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tLaunchpadDo) First() (*model.TLaunchpad, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TLaunchpad), nil
	}
}

func (t tLaunchpadDo) Take() (*model.TLaunchpad, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TLaunchpad), nil
	}
}

func (t tLaunchpadDo) Last() (*model.TLaunchpad, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TLaunchpad), nil
	}
}

func (t tLaunchpadDo) Find() ([]*model.TLaunchpad, error) {
	result, err := t.DO.Find()
	return result.([]*model.TLaunchpad), err
}

func (t tLaunchpadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TLaunchpad, err error) {
	buf := make([]*model.TLaunchpad, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tLaunchpadDo) FindInBatches(result *[]*model.TLaunchpad, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tLaunchpadDo) Attrs(attrs ...field.AssignExpr) ITLaunchpadDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tLaunchpadDo) Assign(attrs ...field.AssignExpr) ITLaunchpadDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tLaunchpadDo) Joins(fields ...field.RelationField) ITLaunchpadDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tLaunchpadDo) Preload(fields ...field.RelationField) ITLaunchpadDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tLaunchpadDo) FirstOrInit() (*model.TLaunchpad, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TLaunchpad), nil
	}
}

func (t tLaunchpadDo) FirstOrCreate() (*model.TLaunchpad, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TLaunchpad), nil
	}
}

func (t tLaunchpadDo) FindByPage(offset int, limit int) (result []*model.TLaunchpad, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tLaunchpadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tLaunchpadDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tLaunchpadDo) Delete(models ...*model.TLaunchpad) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tLaunchpadDo) withDO(do gen.Dao) *tLaunchpadDo {
	t.DO = *do.(*gen.DO)
	return t
}
