// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTPoolDynamic(db *gorm.DB, opts ...gen.DOOption) tPoolDynamic {
	_tPoolDynamic := tPoolDynamic{}

	_tPoolDynamic.tPoolDynamicDo.UseDB(db, opts...)
	_tPoolDynamic.tPoolDynamicDo.UseModel(&model.TPoolDynamic{})

	tableName := _tPoolDynamic.tPoolDynamicDo.TableName()
	_tPoolDynamic.ALL = field.NewAsterisk(tableName)
	_tPoolDynamic.ID = field.NewInt64(tableName, "id")
	_tPoolDynamic.ChainID = field.NewInt64(tableName, "chain_id")
	_tPoolDynamic.Address = field.NewString(tableName, "address")
	_tPoolDynamic.Liquidity0 = field.NewField(tableName, "liquidity0")
	_tPoolDynamic.Liquidity1 = field.NewField(tableName, "liquidity1")
	_tPoolDynamic.Liquidityu = field.NewFloat64(tableName, "liquidityu")
	_tPoolDynamic.Block = field.NewInt64(tableName, "block")
	_tPoolDynamic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tPoolDynamic.fillFieldMap()

	return _tPoolDynamic
}

type tPoolDynamic struct {
	tPoolDynamicDo tPoolDynamicDo

	ALL        field.Asterisk
	ID         field.Int64
	ChainID    field.Int64
	Address    field.String
	Liquidity0 field.Field
	Liquidity1 field.Field
	Liquidityu field.Float64
	Block      field.Int64
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (t tPoolDynamic) Table(newTableName string) *tPoolDynamic {
	t.tPoolDynamicDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tPoolDynamic) As(alias string) *tPoolDynamic {
	t.tPoolDynamicDo.DO = *(t.tPoolDynamicDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tPoolDynamic) updateTableName(table string) *tPoolDynamic {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ChainID = field.NewInt64(table, "chain_id")
	t.Address = field.NewString(table, "address")
	t.Liquidity0 = field.NewField(table, "liquidity0")
	t.Liquidity1 = field.NewField(table, "liquidity1")
	t.Liquidityu = field.NewFloat64(table, "liquidityu")
	t.Block = field.NewInt64(table, "block")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tPoolDynamic) WithContext(ctx context.Context) ITPoolDynamicDo {
	return t.tPoolDynamicDo.WithContext(ctx)
}

func (t tPoolDynamic) TableName() string { return t.tPoolDynamicDo.TableName() }

func (t tPoolDynamic) Alias() string { return t.tPoolDynamicDo.Alias() }

func (t tPoolDynamic) Columns(cols ...field.Expr) gen.Columns {
	return t.tPoolDynamicDo.Columns(cols...)
}

func (t *tPoolDynamic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tPoolDynamic) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["chain_id"] = t.ChainID
	t.fieldMap["address"] = t.Address
	t.fieldMap["liquidity0"] = t.Liquidity0
	t.fieldMap["liquidity1"] = t.Liquidity1
	t.fieldMap["liquidityu"] = t.Liquidityu
	t.fieldMap["block"] = t.Block
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tPoolDynamic) clone(db *gorm.DB) tPoolDynamic {
	t.tPoolDynamicDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tPoolDynamic) replaceDB(db *gorm.DB) tPoolDynamic {
	t.tPoolDynamicDo.ReplaceDB(db)
	return t
}

type tPoolDynamicDo struct{ gen.DO }

type ITPoolDynamicDo interface {
	gen.SubQuery
	Debug() ITPoolDynamicDo
	WithContext(ctx context.Context) ITPoolDynamicDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITPoolDynamicDo
	WriteDB() ITPoolDynamicDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITPoolDynamicDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITPoolDynamicDo
	Not(conds ...gen.Condition) ITPoolDynamicDo
	Or(conds ...gen.Condition) ITPoolDynamicDo
	Select(conds ...field.Expr) ITPoolDynamicDo
	Where(conds ...gen.Condition) ITPoolDynamicDo
	Order(conds ...field.Expr) ITPoolDynamicDo
	Distinct(cols ...field.Expr) ITPoolDynamicDo
	Omit(cols ...field.Expr) ITPoolDynamicDo
	Join(table schema.Tabler, on ...field.Expr) ITPoolDynamicDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITPoolDynamicDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITPoolDynamicDo
	Group(cols ...field.Expr) ITPoolDynamicDo
	Having(conds ...gen.Condition) ITPoolDynamicDo
	Limit(limit int) ITPoolDynamicDo
	Offset(offset int) ITPoolDynamicDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITPoolDynamicDo
	Unscoped() ITPoolDynamicDo
	Create(values ...*model.TPoolDynamic) error
	CreateInBatches(values []*model.TPoolDynamic, batchSize int) error
	Save(values ...*model.TPoolDynamic) error
	First() (*model.TPoolDynamic, error)
	Take() (*model.TPoolDynamic, error)
	Last() (*model.TPoolDynamic, error)
	Find() ([]*model.TPoolDynamic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TPoolDynamic, err error)
	FindInBatches(result *[]*model.TPoolDynamic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TPoolDynamic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITPoolDynamicDo
	Assign(attrs ...field.AssignExpr) ITPoolDynamicDo
	Joins(fields ...field.RelationField) ITPoolDynamicDo
	Preload(fields ...field.RelationField) ITPoolDynamicDo
	FirstOrInit() (*model.TPoolDynamic, error)
	FirstOrCreate() (*model.TPoolDynamic, error)
	FindByPage(offset int, limit int) (result []*model.TPoolDynamic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITPoolDynamicDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tPoolDynamicDo) Debug() ITPoolDynamicDo {
	return t.withDO(t.DO.Debug())
}

func (t tPoolDynamicDo) WithContext(ctx context.Context) ITPoolDynamicDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tPoolDynamicDo) ReadDB() ITPoolDynamicDo {
	return t.Clauses(dbresolver.Read)
}

func (t tPoolDynamicDo) WriteDB() ITPoolDynamicDo {
	return t.Clauses(dbresolver.Write)
}

func (t tPoolDynamicDo) Session(config *gorm.Session) ITPoolDynamicDo {
	return t.withDO(t.DO.Session(config))
}

func (t tPoolDynamicDo) Clauses(conds ...clause.Expression) ITPoolDynamicDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tPoolDynamicDo) Returning(value interface{}, columns ...string) ITPoolDynamicDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tPoolDynamicDo) Not(conds ...gen.Condition) ITPoolDynamicDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tPoolDynamicDo) Or(conds ...gen.Condition) ITPoolDynamicDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tPoolDynamicDo) Select(conds ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tPoolDynamicDo) Where(conds ...gen.Condition) ITPoolDynamicDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tPoolDynamicDo) Order(conds ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tPoolDynamicDo) Distinct(cols ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tPoolDynamicDo) Omit(cols ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tPoolDynamicDo) Join(table schema.Tabler, on ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tPoolDynamicDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tPoolDynamicDo) RightJoin(table schema.Tabler, on ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tPoolDynamicDo) Group(cols ...field.Expr) ITPoolDynamicDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tPoolDynamicDo) Having(conds ...gen.Condition) ITPoolDynamicDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tPoolDynamicDo) Limit(limit int) ITPoolDynamicDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tPoolDynamicDo) Offset(offset int) ITPoolDynamicDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tPoolDynamicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITPoolDynamicDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tPoolDynamicDo) Unscoped() ITPoolDynamicDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tPoolDynamicDo) Create(values ...*model.TPoolDynamic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tPoolDynamicDo) CreateInBatches(values []*model.TPoolDynamic, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tPoolDynamicDo) Save(values ...*model.TPoolDynamic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tPoolDynamicDo) First() (*model.TPoolDynamic, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPoolDynamic), nil
	}
}

func (t tPoolDynamicDo) Take() (*model.TPoolDynamic, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPoolDynamic), nil
	}
}

func (t tPoolDynamicDo) Last() (*model.TPoolDynamic, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPoolDynamic), nil
	}
}

func (t tPoolDynamicDo) Find() ([]*model.TPoolDynamic, error) {
	result, err := t.DO.Find()
	return result.([]*model.TPoolDynamic), err
}

func (t tPoolDynamicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TPoolDynamic, err error) {
	buf := make([]*model.TPoolDynamic, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tPoolDynamicDo) FindInBatches(result *[]*model.TPoolDynamic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tPoolDynamicDo) Attrs(attrs ...field.AssignExpr) ITPoolDynamicDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tPoolDynamicDo) Assign(attrs ...field.AssignExpr) ITPoolDynamicDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tPoolDynamicDo) Joins(fields ...field.RelationField) ITPoolDynamicDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tPoolDynamicDo) Preload(fields ...field.RelationField) ITPoolDynamicDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tPoolDynamicDo) FirstOrInit() (*model.TPoolDynamic, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPoolDynamic), nil
	}
}

func (t tPoolDynamicDo) FirstOrCreate() (*model.TPoolDynamic, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPoolDynamic), nil
	}
}

func (t tPoolDynamicDo) FindByPage(offset int, limit int) (result []*model.TPoolDynamic, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tPoolDynamicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tPoolDynamicDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tPoolDynamicDo) Delete(models ...*model.TPoolDynamic) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tPoolDynamicDo) withDO(do gen.Dao) *tPoolDynamicDo {
	t.DO = *do.(*gen.DO)
	return t
}
