// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTPool(db *gorm.DB, opts ...gen.DOOption) tPool {
	_tPool := tPool{}

	_tPool.tPoolDo.UseDB(db, opts...)
	_tPool.tPoolDo.UseModel(&model.TPool{})

	tableName := _tPool.tPoolDo.TableName()
	_tPool.ALL = field.NewAsterisk(tableName)
	_tPool.ID = field.NewInt64(tableName, "id")
	_tPool.Address = field.NewString(tableName, "address")
	_tPool.ChainID = field.NewInt64(tableName, "chain_id")
	_tPool.DexPoolID = field.NewInt32(tableName, "dex_pool_id")
	_tPool.LaunchpadID = field.NewInt32(tableName, "launchpad_id")
	_tPool.Token0ID = field.NewInt64(tableName, "token0_id")
	_tPool.Token1ID = field.NewInt64(tableName, "token1_id")
	_tPool.FeeBps = field.NewInt32(tableName, "fee_bps")
	_tPool.CreatedAt = field.NewTime(tableName, "created_at")
	_tPool.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tPool.fillFieldMap()

	return _tPool
}

type tPool struct {
	tPoolDo tPoolDo

	ALL         field.Asterisk
	ID          field.Int64
	Address     field.String
	ChainID     field.Int64
	DexPoolID   field.Int32
	LaunchpadID field.Int32
	Token0ID    field.Int64
	Token1ID    field.Int64
	FeeBps      field.Int32
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (t tPool) Table(newTableName string) *tPool {
	t.tPoolDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tPool) As(alias string) *tPool {
	t.tPoolDo.DO = *(t.tPoolDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tPool) updateTableName(table string) *tPool {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Address = field.NewString(table, "address")
	t.ChainID = field.NewInt64(table, "chain_id")
	t.DexPoolID = field.NewInt32(table, "dex_pool_id")
	t.LaunchpadID = field.NewInt32(table, "launchpad_id")
	t.Token0ID = field.NewInt64(table, "token0_id")
	t.Token1ID = field.NewInt64(table, "token1_id")
	t.FeeBps = field.NewInt32(table, "fee_bps")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tPool) WithContext(ctx context.Context) ITPoolDo { return t.tPoolDo.WithContext(ctx) }

func (t tPool) TableName() string { return t.tPoolDo.TableName() }

func (t tPool) Alias() string { return t.tPoolDo.Alias() }

func (t tPool) Columns(cols ...field.Expr) gen.Columns { return t.tPoolDo.Columns(cols...) }

func (t *tPool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tPool) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["address"] = t.Address
	t.fieldMap["chain_id"] = t.ChainID
	t.fieldMap["dex_pool_id"] = t.DexPoolID
	t.fieldMap["launchpad_id"] = t.LaunchpadID
	t.fieldMap["token0_id"] = t.Token0ID
	t.fieldMap["token1_id"] = t.Token1ID
	t.fieldMap["fee_bps"] = t.FeeBps
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tPool) clone(db *gorm.DB) tPool {
	t.tPoolDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tPool) replaceDB(db *gorm.DB) tPool {
	t.tPoolDo.ReplaceDB(db)
	return t
}

type tPoolDo struct{ gen.DO }

type ITPoolDo interface {
	gen.SubQuery
	Debug() ITPoolDo
	WithContext(ctx context.Context) ITPoolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITPoolDo
	WriteDB() ITPoolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITPoolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITPoolDo
	Not(conds ...gen.Condition) ITPoolDo
	Or(conds ...gen.Condition) ITPoolDo
	Select(conds ...field.Expr) ITPoolDo
	Where(conds ...gen.Condition) ITPoolDo
	Order(conds ...field.Expr) ITPoolDo
	Distinct(cols ...field.Expr) ITPoolDo
	Omit(cols ...field.Expr) ITPoolDo
	Join(table schema.Tabler, on ...field.Expr) ITPoolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITPoolDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITPoolDo
	Group(cols ...field.Expr) ITPoolDo
	Having(conds ...gen.Condition) ITPoolDo
	Limit(limit int) ITPoolDo
	Offset(offset int) ITPoolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITPoolDo
	Unscoped() ITPoolDo
	Create(values ...*model.TPool) error
	CreateInBatches(values []*model.TPool, batchSize int) error
	Save(values ...*model.TPool) error
	First() (*model.TPool, error)
	Take() (*model.TPool, error)
	Last() (*model.TPool, error)
	Find() ([]*model.TPool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TPool, err error)
	FindInBatches(result *[]*model.TPool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TPool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITPoolDo
	Assign(attrs ...field.AssignExpr) ITPoolDo
	Joins(fields ...field.RelationField) ITPoolDo
	Preload(fields ...field.RelationField) ITPoolDo
	FirstOrInit() (*model.TPool, error)
	FirstOrCreate() (*model.TPool, error)
	FindByPage(offset int, limit int) (result []*model.TPool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITPoolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tPoolDo) Debug() ITPoolDo {
	return t.withDO(t.DO.Debug())
}

func (t tPoolDo) WithContext(ctx context.Context) ITPoolDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tPoolDo) ReadDB() ITPoolDo {
	return t.Clauses(dbresolver.Read)
}

func (t tPoolDo) WriteDB() ITPoolDo {
	return t.Clauses(dbresolver.Write)
}

func (t tPoolDo) Session(config *gorm.Session) ITPoolDo {
	return t.withDO(t.DO.Session(config))
}

func (t tPoolDo) Clauses(conds ...clause.Expression) ITPoolDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tPoolDo) Returning(value interface{}, columns ...string) ITPoolDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tPoolDo) Not(conds ...gen.Condition) ITPoolDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tPoolDo) Or(conds ...gen.Condition) ITPoolDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tPoolDo) Select(conds ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tPoolDo) Where(conds ...gen.Condition) ITPoolDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tPoolDo) Order(conds ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tPoolDo) Distinct(cols ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tPoolDo) Omit(cols ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tPoolDo) Join(table schema.Tabler, on ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tPoolDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tPoolDo) RightJoin(table schema.Tabler, on ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tPoolDo) Group(cols ...field.Expr) ITPoolDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tPoolDo) Having(conds ...gen.Condition) ITPoolDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tPoolDo) Limit(limit int) ITPoolDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tPoolDo) Offset(offset int) ITPoolDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tPoolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITPoolDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tPoolDo) Unscoped() ITPoolDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tPoolDo) Create(values ...*model.TPool) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tPoolDo) CreateInBatches(values []*model.TPool, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tPoolDo) Save(values ...*model.TPool) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tPoolDo) First() (*model.TPool, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPool), nil
	}
}

func (t tPoolDo) Take() (*model.TPool, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPool), nil
	}
}

func (t tPoolDo) Last() (*model.TPool, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPool), nil
	}
}

func (t tPoolDo) Find() ([]*model.TPool, error) {
	result, err := t.DO.Find()
	return result.([]*model.TPool), err
}

func (t tPoolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TPool, err error) {
	buf := make([]*model.TPool, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tPoolDo) FindInBatches(result *[]*model.TPool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tPoolDo) Attrs(attrs ...field.AssignExpr) ITPoolDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tPoolDo) Assign(attrs ...field.AssignExpr) ITPoolDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tPoolDo) Joins(fields ...field.RelationField) ITPoolDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tPoolDo) Preload(fields ...field.RelationField) ITPoolDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tPoolDo) FirstOrInit() (*model.TPool, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPool), nil
	}
}

func (t tPoolDo) FirstOrCreate() (*model.TPool, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPool), nil
	}
}

func (t tPoolDo) FindByPage(offset int, limit int) (result []*model.TPool, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tPoolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tPoolDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tPoolDo) Delete(models ...*model.TPool) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tPoolDo) withDO(do gen.Dao) *tPoolDo {
	t.DO = *do.(*gen.DO)
	return t
}
