// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTTokenStale(db *gorm.DB, opts ...gen.DOOption) tTokenStale {
	_tTokenStale := tTokenStale{}

	_tTokenStale.tTokenStaleDo.UseDB(db, opts...)
	_tTokenStale.tTokenStaleDo.UseModel(&model.TTokenStale{})

	tableName := _tTokenStale.tTokenStaleDo.TableName()
	_tTokenStale.ALL = field.NewAsterisk(tableName)
	_tTokenStale.ID = field.NewInt64(tableName, "id")
	_tTokenStale.ChainID = field.NewInt64(tableName, "chain_id")
	_tTokenStale.Address = field.NewString(tableName, "address")
	_tTokenStale.Priceu = field.NewFloat64(tableName, "priceu")
	_tTokenStale.BestPoolID = field.NewInt64(tableName, "best_pool_id")
	_tTokenStale.BestPoolVliq = field.NewFloat64(tableName, "best_pool_vliq")
	_tTokenStale.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tTokenStale.fillFieldMap()

	return _tTokenStale
}

type tTokenStale struct {
	tTokenStaleDo tTokenStaleDo

	ALL          field.Asterisk
	ID           field.Int64
	ChainID      field.Int64
	Address      field.String
	Priceu       field.Float64
	BestPoolID   field.Int64
	BestPoolVliq field.Float64
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t tTokenStale) Table(newTableName string) *tTokenStale {
	t.tTokenStaleDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tTokenStale) As(alias string) *tTokenStale {
	t.tTokenStaleDo.DO = *(t.tTokenStaleDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tTokenStale) updateTableName(table string) *tTokenStale {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ChainID = field.NewInt64(table, "chain_id")
	t.Address = field.NewString(table, "address")
	t.Priceu = field.NewFloat64(table, "priceu")
	t.BestPoolID = field.NewInt64(table, "best_pool_id")
	t.BestPoolVliq = field.NewFloat64(table, "best_pool_vliq")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tTokenStale) WithContext(ctx context.Context) ITTokenStaleDo {
	return t.tTokenStaleDo.WithContext(ctx)
}

func (t tTokenStale) TableName() string { return t.tTokenStaleDo.TableName() }

func (t tTokenStale) Alias() string { return t.tTokenStaleDo.Alias() }

func (t tTokenStale) Columns(cols ...field.Expr) gen.Columns { return t.tTokenStaleDo.Columns(cols...) }

func (t *tTokenStale) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tTokenStale) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["chain_id"] = t.ChainID
	t.fieldMap["address"] = t.Address
	t.fieldMap["priceu"] = t.Priceu
	t.fieldMap["best_pool_id"] = t.BestPoolID
	t.fieldMap["best_pool_vliq"] = t.BestPoolVliq
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tTokenStale) clone(db *gorm.DB) tTokenStale {
	t.tTokenStaleDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tTokenStale) replaceDB(db *gorm.DB) tTokenStale {
	t.tTokenStaleDo.ReplaceDB(db)
	return t
}

type tTokenStaleDo struct{ gen.DO }

type ITTokenStaleDo interface {
	gen.SubQuery
	Debug() ITTokenStaleDo
	WithContext(ctx context.Context) ITTokenStaleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITTokenStaleDo
	WriteDB() ITTokenStaleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITTokenStaleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITTokenStaleDo
	Not(conds ...gen.Condition) ITTokenStaleDo
	Or(conds ...gen.Condition) ITTokenStaleDo
	Select(conds ...field.Expr) ITTokenStaleDo
	Where(conds ...gen.Condition) ITTokenStaleDo
	Order(conds ...field.Expr) ITTokenStaleDo
	Distinct(cols ...field.Expr) ITTokenStaleDo
	Omit(cols ...field.Expr) ITTokenStaleDo
	Join(table schema.Tabler, on ...field.Expr) ITTokenStaleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenStaleDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITTokenStaleDo
	Group(cols ...field.Expr) ITTokenStaleDo
	Having(conds ...gen.Condition) ITTokenStaleDo
	Limit(limit int) ITTokenStaleDo
	Offset(offset int) ITTokenStaleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenStaleDo
	Unscoped() ITTokenStaleDo
	Create(values ...*model.TTokenStale) error
	CreateInBatches(values []*model.TTokenStale, batchSize int) error
	Save(values ...*model.TTokenStale) error
	First() (*model.TTokenStale, error)
	Take() (*model.TTokenStale, error)
	Last() (*model.TTokenStale, error)
	Find() ([]*model.TTokenStale, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenStale, err error)
	FindInBatches(result *[]*model.TTokenStale, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TTokenStale) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITTokenStaleDo
	Assign(attrs ...field.AssignExpr) ITTokenStaleDo
	Joins(fields ...field.RelationField) ITTokenStaleDo
	Preload(fields ...field.RelationField) ITTokenStaleDo
	FirstOrInit() (*model.TTokenStale, error)
	FirstOrCreate() (*model.TTokenStale, error)
	FindByPage(offset int, limit int) (result []*model.TTokenStale, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITTokenStaleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tTokenStaleDo) Debug() ITTokenStaleDo {
	return t.withDO(t.DO.Debug())
}

func (t tTokenStaleDo) WithContext(ctx context.Context) ITTokenStaleDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tTokenStaleDo) ReadDB() ITTokenStaleDo {
	return t.Clauses(dbresolver.Read)
}

func (t tTokenStaleDo) WriteDB() ITTokenStaleDo {
	return t.Clauses(dbresolver.Write)
}

func (t tTokenStaleDo) Session(config *gorm.Session) ITTokenStaleDo {
	return t.withDO(t.DO.Session(config))
}

func (t tTokenStaleDo) Clauses(conds ...clause.Expression) ITTokenStaleDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tTokenStaleDo) Returning(value interface{}, columns ...string) ITTokenStaleDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tTokenStaleDo) Not(conds ...gen.Condition) ITTokenStaleDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tTokenStaleDo) Or(conds ...gen.Condition) ITTokenStaleDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tTokenStaleDo) Select(conds ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tTokenStaleDo) Where(conds ...gen.Condition) ITTokenStaleDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tTokenStaleDo) Order(conds ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tTokenStaleDo) Distinct(cols ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tTokenStaleDo) Omit(cols ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tTokenStaleDo) Join(table schema.Tabler, on ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tTokenStaleDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tTokenStaleDo) RightJoin(table schema.Tabler, on ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tTokenStaleDo) Group(cols ...field.Expr) ITTokenStaleDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tTokenStaleDo) Having(conds ...gen.Condition) ITTokenStaleDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tTokenStaleDo) Limit(limit int) ITTokenStaleDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tTokenStaleDo) Offset(offset int) ITTokenStaleDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tTokenStaleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenStaleDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tTokenStaleDo) Unscoped() ITTokenStaleDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tTokenStaleDo) Create(values ...*model.TTokenStale) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tTokenStaleDo) CreateInBatches(values []*model.TTokenStale, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tTokenStaleDo) Save(values ...*model.TTokenStale) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tTokenStaleDo) First() (*model.TTokenStale, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStale), nil
	}
}

func (t tTokenStaleDo) Take() (*model.TTokenStale, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStale), nil
	}
}

func (t tTokenStaleDo) Last() (*model.TTokenStale, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStale), nil
	}
}

func (t tTokenStaleDo) Find() ([]*model.TTokenStale, error) {
	result, err := t.DO.Find()
	return result.([]*model.TTokenStale), err
}

func (t tTokenStaleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenStale, err error) {
	buf := make([]*model.TTokenStale, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tTokenStaleDo) FindInBatches(result *[]*model.TTokenStale, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tTokenStaleDo) Attrs(attrs ...field.AssignExpr) ITTokenStaleDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tTokenStaleDo) Assign(attrs ...field.AssignExpr) ITTokenStaleDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tTokenStaleDo) Joins(fields ...field.RelationField) ITTokenStaleDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tTokenStaleDo) Preload(fields ...field.RelationField) ITTokenStaleDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tTokenStaleDo) FirstOrInit() (*model.TTokenStale, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStale), nil
	}
}

func (t tTokenStaleDo) FirstOrCreate() (*model.TTokenStale, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStale), nil
	}
}

func (t tTokenStaleDo) FindByPage(offset int, limit int) (result []*model.TTokenStale, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tTokenStaleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tTokenStaleDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tTokenStaleDo) Delete(models ...*model.TTokenStale) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tTokenStaleDo) withDO(do gen.Dao) *tTokenStaleDo {
	t.DO = *do.(*gen.DO)
	return t
}
