// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTTokenDynamicStale(db *gorm.DB, opts ...gen.DOOption) tTokenDynamicStale {
	_tTokenDynamicStale := tTokenDynamicStale{}

	_tTokenDynamicStale.tTokenDynamicStaleDo.UseDB(db, opts...)
	_tTokenDynamicStale.tTokenDynamicStaleDo.UseModel(&model.TTokenDynamicStale{})

	tableName := _tTokenDynamicStale.tTokenDynamicStaleDo.TableName()
	_tTokenDynamicStale.ALL = field.NewAsterisk(tableName)
	_tTokenDynamicStale.ID = field.NewInt64(tableName, "id")
	_tTokenDynamicStale.ChainID = field.NewInt64(tableName, "chain_id")
	_tTokenDynamicStale.Address = field.NewString(tableName, "address")
	_tTokenDynamicStale.Priceu = field.NewFloat64(tableName, "priceu")
	_tTokenDynamicStale.BestPoolID = field.NewInt64(tableName, "best_pool_id")
	_tTokenDynamicStale.BestPoolVliq = field.NewFloat64(tableName, "best_pool_vliq")
	_tTokenDynamicStale.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tTokenDynamicStale.fillFieldMap()

	return _tTokenDynamicStale
}

type tTokenDynamicStale struct {
	tTokenDynamicStaleDo tTokenDynamicStaleDo

	ALL          field.Asterisk
	ID           field.Int64
	ChainID      field.Int64
	Address      field.String
	Priceu       field.Float64
	BestPoolID   field.Int64
	BestPoolVliq field.Float64
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t tTokenDynamicStale) Table(newTableName string) *tTokenDynamicStale {
	t.tTokenDynamicStaleDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tTokenDynamicStale) As(alias string) *tTokenDynamicStale {
	t.tTokenDynamicStaleDo.DO = *(t.tTokenDynamicStaleDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tTokenDynamicStale) updateTableName(table string) *tTokenDynamicStale {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ChainID = field.NewInt64(table, "chain_id")
	t.Address = field.NewString(table, "address")
	t.Priceu = field.NewFloat64(table, "priceu")
	t.BestPoolID = field.NewInt64(table, "best_pool_id")
	t.BestPoolVliq = field.NewFloat64(table, "best_pool_vliq")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tTokenDynamicStale) WithContext(ctx context.Context) ITTokenDynamicStaleDo {
	return t.tTokenDynamicStaleDo.WithContext(ctx)
}

func (t tTokenDynamicStale) TableName() string { return t.tTokenDynamicStaleDo.TableName() }

func (t tTokenDynamicStale) Alias() string { return t.tTokenDynamicStaleDo.Alias() }

func (t tTokenDynamicStale) Columns(cols ...field.Expr) gen.Columns {
	return t.tTokenDynamicStaleDo.Columns(cols...)
}

func (t *tTokenDynamicStale) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tTokenDynamicStale) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["chain_id"] = t.ChainID
	t.fieldMap["address"] = t.Address
	t.fieldMap["priceu"] = t.Priceu
	t.fieldMap["best_pool_id"] = t.BestPoolID
	t.fieldMap["best_pool_vliq"] = t.BestPoolVliq
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tTokenDynamicStale) clone(db *gorm.DB) tTokenDynamicStale {
	t.tTokenDynamicStaleDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tTokenDynamicStale) replaceDB(db *gorm.DB) tTokenDynamicStale {
	t.tTokenDynamicStaleDo.ReplaceDB(db)
	return t
}

type tTokenDynamicStaleDo struct{ gen.DO }

type ITTokenDynamicStaleDo interface {
	gen.SubQuery
	Debug() ITTokenDynamicStaleDo
	WithContext(ctx context.Context) ITTokenDynamicStaleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITTokenDynamicStaleDo
	WriteDB() ITTokenDynamicStaleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITTokenDynamicStaleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITTokenDynamicStaleDo
	Not(conds ...gen.Condition) ITTokenDynamicStaleDo
	Or(conds ...gen.Condition) ITTokenDynamicStaleDo
	Select(conds ...field.Expr) ITTokenDynamicStaleDo
	Where(conds ...gen.Condition) ITTokenDynamicStaleDo
	Order(conds ...field.Expr) ITTokenDynamicStaleDo
	Distinct(cols ...field.Expr) ITTokenDynamicStaleDo
	Omit(cols ...field.Expr) ITTokenDynamicStaleDo
	Join(table schema.Tabler, on ...field.Expr) ITTokenDynamicStaleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicStaleDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicStaleDo
	Group(cols ...field.Expr) ITTokenDynamicStaleDo
	Having(conds ...gen.Condition) ITTokenDynamicStaleDo
	Limit(limit int) ITTokenDynamicStaleDo
	Offset(offset int) ITTokenDynamicStaleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenDynamicStaleDo
	Unscoped() ITTokenDynamicStaleDo
	Create(values ...*model.TTokenDynamicStale) error
	CreateInBatches(values []*model.TTokenDynamicStale, batchSize int) error
	Save(values ...*model.TTokenDynamicStale) error
	First() (*model.TTokenDynamicStale, error)
	Take() (*model.TTokenDynamicStale, error)
	Last() (*model.TTokenDynamicStale, error)
	Find() ([]*model.TTokenDynamicStale, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenDynamicStale, err error)
	FindInBatches(result *[]*model.TTokenDynamicStale, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TTokenDynamicStale) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITTokenDynamicStaleDo
	Assign(attrs ...field.AssignExpr) ITTokenDynamicStaleDo
	Joins(fields ...field.RelationField) ITTokenDynamicStaleDo
	Preload(fields ...field.RelationField) ITTokenDynamicStaleDo
	FirstOrInit() (*model.TTokenDynamicStale, error)
	FirstOrCreate() (*model.TTokenDynamicStale, error)
	FindByPage(offset int, limit int) (result []*model.TTokenDynamicStale, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITTokenDynamicStaleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tTokenDynamicStaleDo) Debug() ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Debug())
}

func (t tTokenDynamicStaleDo) WithContext(ctx context.Context) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tTokenDynamicStaleDo) ReadDB() ITTokenDynamicStaleDo {
	return t.Clauses(dbresolver.Read)
}

func (t tTokenDynamicStaleDo) WriteDB() ITTokenDynamicStaleDo {
	return t.Clauses(dbresolver.Write)
}

func (t tTokenDynamicStaleDo) Session(config *gorm.Session) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Session(config))
}

func (t tTokenDynamicStaleDo) Clauses(conds ...clause.Expression) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tTokenDynamicStaleDo) Returning(value interface{}, columns ...string) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tTokenDynamicStaleDo) Not(conds ...gen.Condition) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tTokenDynamicStaleDo) Or(conds ...gen.Condition) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tTokenDynamicStaleDo) Select(conds ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tTokenDynamicStaleDo) Where(conds ...gen.Condition) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tTokenDynamicStaleDo) Order(conds ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tTokenDynamicStaleDo) Distinct(cols ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tTokenDynamicStaleDo) Omit(cols ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tTokenDynamicStaleDo) Join(table schema.Tabler, on ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tTokenDynamicStaleDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tTokenDynamicStaleDo) RightJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tTokenDynamicStaleDo) Group(cols ...field.Expr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tTokenDynamicStaleDo) Having(conds ...gen.Condition) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tTokenDynamicStaleDo) Limit(limit int) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tTokenDynamicStaleDo) Offset(offset int) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tTokenDynamicStaleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tTokenDynamicStaleDo) Unscoped() ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tTokenDynamicStaleDo) Create(values ...*model.TTokenDynamicStale) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tTokenDynamicStaleDo) CreateInBatches(values []*model.TTokenDynamicStale, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tTokenDynamicStaleDo) Save(values ...*model.TTokenDynamicStale) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tTokenDynamicStaleDo) First() (*model.TTokenDynamicStale, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamicStale), nil
	}
}

func (t tTokenDynamicStaleDo) Take() (*model.TTokenDynamicStale, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamicStale), nil
	}
}

func (t tTokenDynamicStaleDo) Last() (*model.TTokenDynamicStale, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamicStale), nil
	}
}

func (t tTokenDynamicStaleDo) Find() ([]*model.TTokenDynamicStale, error) {
	result, err := t.DO.Find()
	return result.([]*model.TTokenDynamicStale), err
}

func (t tTokenDynamicStaleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenDynamicStale, err error) {
	buf := make([]*model.TTokenDynamicStale, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tTokenDynamicStaleDo) FindInBatches(result *[]*model.TTokenDynamicStale, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tTokenDynamicStaleDo) Attrs(attrs ...field.AssignExpr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tTokenDynamicStaleDo) Assign(attrs ...field.AssignExpr) ITTokenDynamicStaleDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tTokenDynamicStaleDo) Joins(fields ...field.RelationField) ITTokenDynamicStaleDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tTokenDynamicStaleDo) Preload(fields ...field.RelationField) ITTokenDynamicStaleDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tTokenDynamicStaleDo) FirstOrInit() (*model.TTokenDynamicStale, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamicStale), nil
	}
}

func (t tTokenDynamicStaleDo) FirstOrCreate() (*model.TTokenDynamicStale, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamicStale), nil
	}
}

func (t tTokenDynamicStaleDo) FindByPage(offset int, limit int) (result []*model.TTokenDynamicStale, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tTokenDynamicStaleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tTokenDynamicStaleDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tTokenDynamicStaleDo) Delete(models ...*model.TTokenDynamicStale) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tTokenDynamicStaleDo) withDO(do gen.Dao) *tTokenDynamicStaleDo {
	t.DO = *do.(*gen.DO)
	return t
}
