// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTTokenStatic(db *gorm.DB, opts ...gen.DOOption) tTokenStatic {
	_tTokenStatic := tTokenStatic{}

	_tTokenStatic.tTokenStaticDo.UseDB(db, opts...)
	_tTokenStatic.tTokenStaticDo.UseModel(&model.TTokenStatic{})

	tableName := _tTokenStatic.tTokenStaticDo.TableName()
	_tTokenStatic.ALL = field.NewAsterisk(tableName)
	_tTokenStatic.TokenID = field.NewInt64(tableName, "token_id")
	_tTokenStatic.Symbol = field.NewString(tableName, "symbol")
	_tTokenStatic.Decimals = field.NewInt32(tableName, "decimals")
	_tTokenStatic.FullName = field.NewString(tableName, "full_name")
	_tTokenStatic.CirculatingSupply = field.NewField(tableName, "circulating_supply")
	_tTokenStatic.TotalSupply = field.NewField(tableName, "total_supply")
	_tTokenStatic.DiscoverAt = field.NewTime(tableName, "discover_at")
	_tTokenStatic.Icon = field.NewString(tableName, "icon")
	_tTokenStatic.Twitter = field.NewString(tableName, "twitter")
	_tTokenStatic.Telegram = field.NewString(tableName, "telegram")
	_tTokenStatic.Website = field.NewString(tableName, "website")
	_tTokenStatic.Discord = field.NewString(tableName, "discord")
	_tTokenStatic.Comment = field.NewString(tableName, "comment")
	_tTokenStatic.Flags = field.NewInt32(tableName, "flags")
	_tTokenStatic.CreatedAt = field.NewTime(tableName, "created_at")
	_tTokenStatic.UpdateAt = field.NewTime(tableName, "update_at")

	_tTokenStatic.fillFieldMap()

	return _tTokenStatic
}

type tTokenStatic struct {
	tTokenStaticDo tTokenStaticDo

	ALL               field.Asterisk
	TokenID           field.Int64
	Symbol            field.String
	Decimals          field.Int32
	FullName          field.String
	CirculatingSupply field.Field
	TotalSupply       field.Field
	DiscoverAt        field.Time
	Icon              field.String
	Twitter           field.String
	Telegram          field.String
	Website           field.String
	Discord           field.String
	Comment           field.String
	Flags             field.Int32
	CreatedAt         field.Time
	UpdateAt          field.Time

	fieldMap map[string]field.Expr
}

func (t tTokenStatic) Table(newTableName string) *tTokenStatic {
	t.tTokenStaticDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tTokenStatic) As(alias string) *tTokenStatic {
	t.tTokenStaticDo.DO = *(t.tTokenStaticDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tTokenStatic) updateTableName(table string) *tTokenStatic {
	t.ALL = field.NewAsterisk(table)
	t.TokenID = field.NewInt64(table, "token_id")
	t.Symbol = field.NewString(table, "symbol")
	t.Decimals = field.NewInt32(table, "decimals")
	t.FullName = field.NewString(table, "full_name")
	t.CirculatingSupply = field.NewField(table, "circulating_supply")
	t.TotalSupply = field.NewField(table, "total_supply")
	t.DiscoverAt = field.NewTime(table, "discover_at")
	t.Icon = field.NewString(table, "icon")
	t.Twitter = field.NewString(table, "twitter")
	t.Telegram = field.NewString(table, "telegram")
	t.Website = field.NewString(table, "website")
	t.Discord = field.NewString(table, "discord")
	t.Comment = field.NewString(table, "comment")
	t.Flags = field.NewInt32(table, "flags")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdateAt = field.NewTime(table, "update_at")

	t.fillFieldMap()

	return t
}

func (t *tTokenStatic) WithContext(ctx context.Context) ITTokenStaticDo {
	return t.tTokenStaticDo.WithContext(ctx)
}

func (t tTokenStatic) TableName() string { return t.tTokenStaticDo.TableName() }

func (t tTokenStatic) Alias() string { return t.tTokenStaticDo.Alias() }

func (t tTokenStatic) Columns(cols ...field.Expr) gen.Columns {
	return t.tTokenStaticDo.Columns(cols...)
}

func (t *tTokenStatic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tTokenStatic) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 16)
	t.fieldMap["token_id"] = t.TokenID
	t.fieldMap["symbol"] = t.Symbol
	t.fieldMap["decimals"] = t.Decimals
	t.fieldMap["full_name"] = t.FullName
	t.fieldMap["circulating_supply"] = t.CirculatingSupply
	t.fieldMap["total_supply"] = t.TotalSupply
	t.fieldMap["discover_at"] = t.DiscoverAt
	t.fieldMap["icon"] = t.Icon
	t.fieldMap["twitter"] = t.Twitter
	t.fieldMap["telegram"] = t.Telegram
	t.fieldMap["website"] = t.Website
	t.fieldMap["discord"] = t.Discord
	t.fieldMap["comment"] = t.Comment
	t.fieldMap["flags"] = t.Flags
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["update_at"] = t.UpdateAt
}

func (t tTokenStatic) clone(db *gorm.DB) tTokenStatic {
	t.tTokenStaticDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tTokenStatic) replaceDB(db *gorm.DB) tTokenStatic {
	t.tTokenStaticDo.ReplaceDB(db)
	return t
}

type tTokenStaticDo struct{ gen.DO }

type ITTokenStaticDo interface {
	gen.SubQuery
	Debug() ITTokenStaticDo
	WithContext(ctx context.Context) ITTokenStaticDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITTokenStaticDo
	WriteDB() ITTokenStaticDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITTokenStaticDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITTokenStaticDo
	Not(conds ...gen.Condition) ITTokenStaticDo
	Or(conds ...gen.Condition) ITTokenStaticDo
	Select(conds ...field.Expr) ITTokenStaticDo
	Where(conds ...gen.Condition) ITTokenStaticDo
	Order(conds ...field.Expr) ITTokenStaticDo
	Distinct(cols ...field.Expr) ITTokenStaticDo
	Omit(cols ...field.Expr) ITTokenStaticDo
	Join(table schema.Tabler, on ...field.Expr) ITTokenStaticDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenStaticDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITTokenStaticDo
	Group(cols ...field.Expr) ITTokenStaticDo
	Having(conds ...gen.Condition) ITTokenStaticDo
	Limit(limit int) ITTokenStaticDo
	Offset(offset int) ITTokenStaticDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenStaticDo
	Unscoped() ITTokenStaticDo
	Create(values ...*model.TTokenStatic) error
	CreateInBatches(values []*model.TTokenStatic, batchSize int) error
	Save(values ...*model.TTokenStatic) error
	First() (*model.TTokenStatic, error)
	Take() (*model.TTokenStatic, error)
	Last() (*model.TTokenStatic, error)
	Find() ([]*model.TTokenStatic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenStatic, err error)
	FindInBatches(result *[]*model.TTokenStatic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TTokenStatic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITTokenStaticDo
	Assign(attrs ...field.AssignExpr) ITTokenStaticDo
	Joins(fields ...field.RelationField) ITTokenStaticDo
	Preload(fields ...field.RelationField) ITTokenStaticDo
	FirstOrInit() (*model.TTokenStatic, error)
	FirstOrCreate() (*model.TTokenStatic, error)
	FindByPage(offset int, limit int) (result []*model.TTokenStatic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITTokenStaticDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tTokenStaticDo) Debug() ITTokenStaticDo {
	return t.withDO(t.DO.Debug())
}

func (t tTokenStaticDo) WithContext(ctx context.Context) ITTokenStaticDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tTokenStaticDo) ReadDB() ITTokenStaticDo {
	return t.Clauses(dbresolver.Read)
}

func (t tTokenStaticDo) WriteDB() ITTokenStaticDo {
	return t.Clauses(dbresolver.Write)
}

func (t tTokenStaticDo) Session(config *gorm.Session) ITTokenStaticDo {
	return t.withDO(t.DO.Session(config))
}

func (t tTokenStaticDo) Clauses(conds ...clause.Expression) ITTokenStaticDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tTokenStaticDo) Returning(value interface{}, columns ...string) ITTokenStaticDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tTokenStaticDo) Not(conds ...gen.Condition) ITTokenStaticDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tTokenStaticDo) Or(conds ...gen.Condition) ITTokenStaticDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tTokenStaticDo) Select(conds ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tTokenStaticDo) Where(conds ...gen.Condition) ITTokenStaticDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tTokenStaticDo) Order(conds ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tTokenStaticDo) Distinct(cols ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tTokenStaticDo) Omit(cols ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tTokenStaticDo) Join(table schema.Tabler, on ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tTokenStaticDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tTokenStaticDo) RightJoin(table schema.Tabler, on ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tTokenStaticDo) Group(cols ...field.Expr) ITTokenStaticDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tTokenStaticDo) Having(conds ...gen.Condition) ITTokenStaticDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tTokenStaticDo) Limit(limit int) ITTokenStaticDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tTokenStaticDo) Offset(offset int) ITTokenStaticDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tTokenStaticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenStaticDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tTokenStaticDo) Unscoped() ITTokenStaticDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tTokenStaticDo) Create(values ...*model.TTokenStatic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tTokenStaticDo) CreateInBatches(values []*model.TTokenStatic, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tTokenStaticDo) Save(values ...*model.TTokenStatic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tTokenStaticDo) First() (*model.TTokenStatic, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStatic), nil
	}
}

func (t tTokenStaticDo) Take() (*model.TTokenStatic, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStatic), nil
	}
}

func (t tTokenStaticDo) Last() (*model.TTokenStatic, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStatic), nil
	}
}

func (t tTokenStaticDo) Find() ([]*model.TTokenStatic, error) {
	result, err := t.DO.Find()
	return result.([]*model.TTokenStatic), err
}

func (t tTokenStaticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenStatic, err error) {
	buf := make([]*model.TTokenStatic, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tTokenStaticDo) FindInBatches(result *[]*model.TTokenStatic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tTokenStaticDo) Attrs(attrs ...field.AssignExpr) ITTokenStaticDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tTokenStaticDo) Assign(attrs ...field.AssignExpr) ITTokenStaticDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tTokenStaticDo) Joins(fields ...field.RelationField) ITTokenStaticDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tTokenStaticDo) Preload(fields ...field.RelationField) ITTokenStaticDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tTokenStaticDo) FirstOrInit() (*model.TTokenStatic, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStatic), nil
	}
}

func (t tTokenStaticDo) FirstOrCreate() (*model.TTokenStatic, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenStatic), nil
	}
}

func (t tTokenStaticDo) FindByPage(offset int, limit int) (result []*model.TTokenStatic, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tTokenStaticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tTokenStaticDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tTokenStaticDo) Delete(models ...*model.TTokenStatic) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tTokenStaticDo) withDO(do gen.Dao) *tTokenStaticDo {
	t.DO = *do.(*gen.DO)
	return t
}
