// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTTokenDynamic(db *gorm.DB, opts ...gen.DOOption) tTokenDynamic {
	_tTokenDynamic := tTokenDynamic{}

	_tTokenDynamic.tTokenDynamicDo.UseDB(db, opts...)
	_tTokenDynamic.tTokenDynamicDo.UseModel(&model.TTokenDynamic{})

	tableName := _tTokenDynamic.tTokenDynamicDo.TableName()
	_tTokenDynamic.ALL = field.NewAsterisk(tableName)
	_tTokenDynamic.ID = field.NewInt64(tableName, "id")
	_tTokenDynamic.ChainID = field.NewInt64(tableName, "chain_id")
	_tTokenDynamic.Address = field.NewString(tableName, "address")
	_tTokenDynamic.Priceu = field.NewFloat64(tableName, "priceu")
	_tTokenDynamic.BestPoolID = field.NewInt64(tableName, "best_pool_id")
	_tTokenDynamic.BestPoolVliq = field.NewFloat64(tableName, "best_pool_vliq")
	_tTokenDynamic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tTokenDynamic.fillFieldMap()

	return _tTokenDynamic
}

type tTokenDynamic struct {
	tTokenDynamicDo tTokenDynamicDo

	ALL          field.Asterisk
	ID           field.Int64
	ChainID      field.Int64
	Address      field.String
	Priceu       field.Float64
	BestPoolID   field.Int64
	BestPoolVliq field.Float64
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t tTokenDynamic) Table(newTableName string) *tTokenDynamic {
	t.tTokenDynamicDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tTokenDynamic) As(alias string) *tTokenDynamic {
	t.tTokenDynamicDo.DO = *(t.tTokenDynamicDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tTokenDynamic) updateTableName(table string) *tTokenDynamic {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ChainID = field.NewInt64(table, "chain_id")
	t.Address = field.NewString(table, "address")
	t.Priceu = field.NewFloat64(table, "priceu")
	t.BestPoolID = field.NewInt64(table, "best_pool_id")
	t.BestPoolVliq = field.NewFloat64(table, "best_pool_vliq")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tTokenDynamic) WithContext(ctx context.Context) ITTokenDynamicDo {
	return t.tTokenDynamicDo.WithContext(ctx)
}

func (t tTokenDynamic) TableName() string { return t.tTokenDynamicDo.TableName() }

func (t tTokenDynamic) Alias() string { return t.tTokenDynamicDo.Alias() }

func (t tTokenDynamic) Columns(cols ...field.Expr) gen.Columns {
	return t.tTokenDynamicDo.Columns(cols...)
}

func (t *tTokenDynamic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tTokenDynamic) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["chain_id"] = t.ChainID
	t.fieldMap["address"] = t.Address
	t.fieldMap["priceu"] = t.Priceu
	t.fieldMap["best_pool_id"] = t.BestPoolID
	t.fieldMap["best_pool_vliq"] = t.BestPoolVliq
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tTokenDynamic) clone(db *gorm.DB) tTokenDynamic {
	t.tTokenDynamicDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tTokenDynamic) replaceDB(db *gorm.DB) tTokenDynamic {
	t.tTokenDynamicDo.ReplaceDB(db)
	return t
}

type tTokenDynamicDo struct{ gen.DO }

type ITTokenDynamicDo interface {
	gen.SubQuery
	Debug() ITTokenDynamicDo
	WithContext(ctx context.Context) ITTokenDynamicDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITTokenDynamicDo
	WriteDB() ITTokenDynamicDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITTokenDynamicDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITTokenDynamicDo
	Not(conds ...gen.Condition) ITTokenDynamicDo
	Or(conds ...gen.Condition) ITTokenDynamicDo
	Select(conds ...field.Expr) ITTokenDynamicDo
	Where(conds ...gen.Condition) ITTokenDynamicDo
	Order(conds ...field.Expr) ITTokenDynamicDo
	Distinct(cols ...field.Expr) ITTokenDynamicDo
	Omit(cols ...field.Expr) ITTokenDynamicDo
	Join(table schema.Tabler, on ...field.Expr) ITTokenDynamicDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicDo
	Group(cols ...field.Expr) ITTokenDynamicDo
	Having(conds ...gen.Condition) ITTokenDynamicDo
	Limit(limit int) ITTokenDynamicDo
	Offset(offset int) ITTokenDynamicDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenDynamicDo
	Unscoped() ITTokenDynamicDo
	Create(values ...*model.TTokenDynamic) error
	CreateInBatches(values []*model.TTokenDynamic, batchSize int) error
	Save(values ...*model.TTokenDynamic) error
	First() (*model.TTokenDynamic, error)
	Take() (*model.TTokenDynamic, error)
	Last() (*model.TTokenDynamic, error)
	Find() ([]*model.TTokenDynamic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenDynamic, err error)
	FindInBatches(result *[]*model.TTokenDynamic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TTokenDynamic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITTokenDynamicDo
	Assign(attrs ...field.AssignExpr) ITTokenDynamicDo
	Joins(fields ...field.RelationField) ITTokenDynamicDo
	Preload(fields ...field.RelationField) ITTokenDynamicDo
	FirstOrInit() (*model.TTokenDynamic, error)
	FirstOrCreate() (*model.TTokenDynamic, error)
	FindByPage(offset int, limit int) (result []*model.TTokenDynamic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITTokenDynamicDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tTokenDynamicDo) Debug() ITTokenDynamicDo {
	return t.withDO(t.DO.Debug())
}

func (t tTokenDynamicDo) WithContext(ctx context.Context) ITTokenDynamicDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tTokenDynamicDo) ReadDB() ITTokenDynamicDo {
	return t.Clauses(dbresolver.Read)
}

func (t tTokenDynamicDo) WriteDB() ITTokenDynamicDo {
	return t.Clauses(dbresolver.Write)
}

func (t tTokenDynamicDo) Session(config *gorm.Session) ITTokenDynamicDo {
	return t.withDO(t.DO.Session(config))
}

func (t tTokenDynamicDo) Clauses(conds ...clause.Expression) ITTokenDynamicDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tTokenDynamicDo) Returning(value interface{}, columns ...string) ITTokenDynamicDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tTokenDynamicDo) Not(conds ...gen.Condition) ITTokenDynamicDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tTokenDynamicDo) Or(conds ...gen.Condition) ITTokenDynamicDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tTokenDynamicDo) Select(conds ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tTokenDynamicDo) Where(conds ...gen.Condition) ITTokenDynamicDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tTokenDynamicDo) Order(conds ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tTokenDynamicDo) Distinct(cols ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tTokenDynamicDo) Omit(cols ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tTokenDynamicDo) Join(table schema.Tabler, on ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tTokenDynamicDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tTokenDynamicDo) RightJoin(table schema.Tabler, on ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tTokenDynamicDo) Group(cols ...field.Expr) ITTokenDynamicDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tTokenDynamicDo) Having(conds ...gen.Condition) ITTokenDynamicDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tTokenDynamicDo) Limit(limit int) ITTokenDynamicDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tTokenDynamicDo) Offset(offset int) ITTokenDynamicDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tTokenDynamicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenDynamicDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tTokenDynamicDo) Unscoped() ITTokenDynamicDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tTokenDynamicDo) Create(values ...*model.TTokenDynamic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tTokenDynamicDo) CreateInBatches(values []*model.TTokenDynamic, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tTokenDynamicDo) Save(values ...*model.TTokenDynamic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tTokenDynamicDo) First() (*model.TTokenDynamic, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamic), nil
	}
}

func (t tTokenDynamicDo) Take() (*model.TTokenDynamic, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamic), nil
	}
}

func (t tTokenDynamicDo) Last() (*model.TTokenDynamic, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamic), nil
	}
}

func (t tTokenDynamicDo) Find() ([]*model.TTokenDynamic, error) {
	result, err := t.DO.Find()
	return result.([]*model.TTokenDynamic), err
}

func (t tTokenDynamicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTokenDynamic, err error) {
	buf := make([]*model.TTokenDynamic, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tTokenDynamicDo) FindInBatches(result *[]*model.TTokenDynamic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tTokenDynamicDo) Attrs(attrs ...field.AssignExpr) ITTokenDynamicDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tTokenDynamicDo) Assign(attrs ...field.AssignExpr) ITTokenDynamicDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tTokenDynamicDo) Joins(fields ...field.RelationField) ITTokenDynamicDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tTokenDynamicDo) Preload(fields ...field.RelationField) ITTokenDynamicDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tTokenDynamicDo) FirstOrInit() (*model.TTokenDynamic, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamic), nil
	}
}

func (t tTokenDynamicDo) FirstOrCreate() (*model.TTokenDynamic, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTokenDynamic), nil
	}
}

func (t tTokenDynamicDo) FindByPage(offset int, limit int) (result []*model.TTokenDynamic, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tTokenDynamicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tTokenDynamicDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tTokenDynamicDo) Delete(models ...*model.TTokenDynamic) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tTokenDynamicDo) withDO(do gen.Dao) *tTokenDynamicDo {
	t.DO = *do.(*gen.DO)
	return t
}
