// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTToken(db *gorm.DB, opts ...gen.DOOption) tToken {
	_tToken := tToken{}

	_tToken.tTokenDo.UseDB(db, opts...)
	_tToken.tTokenDo.UseModel(&model.TToken{})

	tableName := _tToken.tTokenDo.TableName()
	_tToken.ALL = field.NewAsterisk(tableName)
	_tToken.ID = field.NewInt64(tableName, "id")
	_tToken.ChainID = field.NewInt64(tableName, "chain_id")
	_tToken.Address = field.NewString(tableName, "address")
	_tToken.Priceu = field.NewFloat64(tableName, "priceu")
	_tToken.BestPoolID = field.NewInt64(tableName, "best_pool_id")
	_tToken.BestPoolVliq = field.NewFloat64(tableName, "best_pool_vliq")
	_tToken.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tToken.fillFieldMap()

	return _tToken
}

type tToken struct {
	tTokenDo tTokenDo

	ALL          field.Asterisk
	ID           field.Int64
	ChainID      field.Int64
	Address      field.String
	Priceu       field.Float64
	BestPoolID   field.Int64
	BestPoolVliq field.Float64
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t tToken) Table(newTableName string) *tToken {
	t.tTokenDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tToken) As(alias string) *tToken {
	t.tTokenDo.DO = *(t.tTokenDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tToken) updateTableName(table string) *tToken {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ChainID = field.NewInt64(table, "chain_id")
	t.Address = field.NewString(table, "address")
	t.Priceu = field.NewFloat64(table, "priceu")
	t.BestPoolID = field.NewInt64(table, "best_pool_id")
	t.BestPoolVliq = field.NewFloat64(table, "best_pool_vliq")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tToken) WithContext(ctx context.Context) ITTokenDo { return t.tTokenDo.WithContext(ctx) }

func (t tToken) TableName() string { return t.tTokenDo.TableName() }

func (t tToken) Alias() string { return t.tTokenDo.Alias() }

func (t tToken) Columns(cols ...field.Expr) gen.Columns { return t.tTokenDo.Columns(cols...) }

func (t *tToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tToken) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["chain_id"] = t.ChainID
	t.fieldMap["address"] = t.Address
	t.fieldMap["priceu"] = t.Priceu
	t.fieldMap["best_pool_id"] = t.BestPoolID
	t.fieldMap["best_pool_vliq"] = t.BestPoolVliq
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tToken) clone(db *gorm.DB) tToken {
	t.tTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tToken) replaceDB(db *gorm.DB) tToken {
	t.tTokenDo.ReplaceDB(db)
	return t
}

type tTokenDo struct{ gen.DO }

type ITTokenDo interface {
	gen.SubQuery
	Debug() ITTokenDo
	WithContext(ctx context.Context) ITTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITTokenDo
	WriteDB() ITTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITTokenDo
	Not(conds ...gen.Condition) ITTokenDo
	Or(conds ...gen.Condition) ITTokenDo
	Select(conds ...field.Expr) ITTokenDo
	Where(conds ...gen.Condition) ITTokenDo
	Order(conds ...field.Expr) ITTokenDo
	Distinct(cols ...field.Expr) ITTokenDo
	Omit(cols ...field.Expr) ITTokenDo
	Join(table schema.Tabler, on ...field.Expr) ITTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITTokenDo
	Group(cols ...field.Expr) ITTokenDo
	Having(conds ...gen.Condition) ITTokenDo
	Limit(limit int) ITTokenDo
	Offset(offset int) ITTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenDo
	Unscoped() ITTokenDo
	Create(values ...*model.TToken) error
	CreateInBatches(values []*model.TToken, batchSize int) error
	Save(values ...*model.TToken) error
	First() (*model.TToken, error)
	Take() (*model.TToken, error)
	Last() (*model.TToken, error)
	Find() ([]*model.TToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TToken, err error)
	FindInBatches(result *[]*model.TToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITTokenDo
	Assign(attrs ...field.AssignExpr) ITTokenDo
	Joins(fields ...field.RelationField) ITTokenDo
	Preload(fields ...field.RelationField) ITTokenDo
	FirstOrInit() (*model.TToken, error)
	FirstOrCreate() (*model.TToken, error)
	FindByPage(offset int, limit int) (result []*model.TToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tTokenDo) Debug() ITTokenDo {
	return t.withDO(t.DO.Debug())
}

func (t tTokenDo) WithContext(ctx context.Context) ITTokenDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tTokenDo) ReadDB() ITTokenDo {
	return t.Clauses(dbresolver.Read)
}

func (t tTokenDo) WriteDB() ITTokenDo {
	return t.Clauses(dbresolver.Write)
}

func (t tTokenDo) Session(config *gorm.Session) ITTokenDo {
	return t.withDO(t.DO.Session(config))
}

func (t tTokenDo) Clauses(conds ...clause.Expression) ITTokenDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tTokenDo) Returning(value interface{}, columns ...string) ITTokenDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tTokenDo) Not(conds ...gen.Condition) ITTokenDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tTokenDo) Or(conds ...gen.Condition) ITTokenDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tTokenDo) Select(conds ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tTokenDo) Where(conds ...gen.Condition) ITTokenDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tTokenDo) Order(conds ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tTokenDo) Distinct(cols ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tTokenDo) Omit(cols ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tTokenDo) Join(table schema.Tabler, on ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tTokenDo) Group(cols ...field.Expr) ITTokenDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tTokenDo) Having(conds ...gen.Condition) ITTokenDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tTokenDo) Limit(limit int) ITTokenDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tTokenDo) Offset(offset int) ITTokenDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITTokenDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tTokenDo) Unscoped() ITTokenDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tTokenDo) Create(values ...*model.TToken) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tTokenDo) CreateInBatches(values []*model.TToken, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tTokenDo) Save(values ...*model.TToken) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tTokenDo) First() (*model.TToken, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TToken), nil
	}
}

func (t tTokenDo) Take() (*model.TToken, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TToken), nil
	}
}

func (t tTokenDo) Last() (*model.TToken, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TToken), nil
	}
}

func (t tTokenDo) Find() ([]*model.TToken, error) {
	result, err := t.DO.Find()
	return result.([]*model.TToken), err
}

func (t tTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TToken, err error) {
	buf := make([]*model.TToken, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tTokenDo) FindInBatches(result *[]*model.TToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tTokenDo) Attrs(attrs ...field.AssignExpr) ITTokenDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tTokenDo) Assign(attrs ...field.AssignExpr) ITTokenDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tTokenDo) Joins(fields ...field.RelationField) ITTokenDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tTokenDo) Preload(fields ...field.RelationField) ITTokenDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tTokenDo) FirstOrInit() (*model.TToken, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TToken), nil
	}
}

func (t tTokenDo) FirstOrCreate() (*model.TToken, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TToken), nil
	}
}

func (t tTokenDo) FindByPage(offset int, limit int) (result []*model.TToken, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tTokenDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tTokenDo) Delete(models ...*model.TToken) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tTokenDo) withDO(do gen.Dao) *tTokenDo {
	t.DO = *do.(*gen.DO)
	return t
}
