// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTUserAddress(db *gorm.DB, opts ...gen.DOOption) tUserAddress {
	_tUserAddress := tUserAddress{}

	_tUserAddress.tUserAddressDo.UseDB(db, opts...)
	_tUserAddress.tUserAddressDo.UseModel(&model.TUserAddress{})

	tableName := _tUserAddress.tUserAddressDo.TableName()
	_tUserAddress.ALL = field.NewAsterisk(tableName)
	_tUserAddress.ID = field.NewInt64(tableName, "id")
	_tUserAddress.UID = field.NewInt64(tableName, "uid")
	_tUserAddress.Network = field.NewInt32(tableName, "network")
	_tUserAddress.Sn = field.NewInt32(tableName, "sn")
	_tUserAddress.Address = field.NewString(tableName, "address")
	_tUserAddress.CreateAt = field.NewTime(tableName, "create_at")
	_tUserAddress.UpdateAt = field.NewTime(tableName, "update_at")

	_tUserAddress.fillFieldMap()

	return _tUserAddress
}

type tUserAddress struct {
	tUserAddressDo tUserAddressDo

	ALL      field.Asterisk
	ID       field.Int64
	UID      field.Int64
	Network  field.Int32
	Sn       field.Int32
	Address  field.String
	CreateAt field.Time
	UpdateAt field.Time

	fieldMap map[string]field.Expr
}

func (t tUserAddress) Table(newTableName string) *tUserAddress {
	t.tUserAddressDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tUserAddress) As(alias string) *tUserAddress {
	t.tUserAddressDo.DO = *(t.tUserAddressDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tUserAddress) updateTableName(table string) *tUserAddress {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.UID = field.NewInt64(table, "uid")
	t.Network = field.NewInt32(table, "network")
	t.Sn = field.NewInt32(table, "sn")
	t.Address = field.NewString(table, "address")
	t.CreateAt = field.NewTime(table, "create_at")
	t.UpdateAt = field.NewTime(table, "update_at")

	t.fillFieldMap()

	return t
}

func (t *tUserAddress) WithContext(ctx context.Context) ITUserAddressDo {
	return t.tUserAddressDo.WithContext(ctx)
}

func (t tUserAddress) TableName() string { return t.tUserAddressDo.TableName() }

func (t tUserAddress) Alias() string { return t.tUserAddressDo.Alias() }

func (t tUserAddress) Columns(cols ...field.Expr) gen.Columns {
	return t.tUserAddressDo.Columns(cols...)
}

func (t *tUserAddress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tUserAddress) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["uid"] = t.UID
	t.fieldMap["network"] = t.Network
	t.fieldMap["sn"] = t.Sn
	t.fieldMap["address"] = t.Address
	t.fieldMap["create_at"] = t.CreateAt
	t.fieldMap["update_at"] = t.UpdateAt
}

func (t tUserAddress) clone(db *gorm.DB) tUserAddress {
	t.tUserAddressDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tUserAddress) replaceDB(db *gorm.DB) tUserAddress {
	t.tUserAddressDo.ReplaceDB(db)
	return t
}

type tUserAddressDo struct{ gen.DO }

type ITUserAddressDo interface {
	gen.SubQuery
	Debug() ITUserAddressDo
	WithContext(ctx context.Context) ITUserAddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITUserAddressDo
	WriteDB() ITUserAddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITUserAddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITUserAddressDo
	Not(conds ...gen.Condition) ITUserAddressDo
	Or(conds ...gen.Condition) ITUserAddressDo
	Select(conds ...field.Expr) ITUserAddressDo
	Where(conds ...gen.Condition) ITUserAddressDo
	Order(conds ...field.Expr) ITUserAddressDo
	Distinct(cols ...field.Expr) ITUserAddressDo
	Omit(cols ...field.Expr) ITUserAddressDo
	Join(table schema.Tabler, on ...field.Expr) ITUserAddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITUserAddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITUserAddressDo
	Group(cols ...field.Expr) ITUserAddressDo
	Having(conds ...gen.Condition) ITUserAddressDo
	Limit(limit int) ITUserAddressDo
	Offset(offset int) ITUserAddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITUserAddressDo
	Unscoped() ITUserAddressDo
	Create(values ...*model.TUserAddress) error
	CreateInBatches(values []*model.TUserAddress, batchSize int) error
	Save(values ...*model.TUserAddress) error
	First() (*model.TUserAddress, error)
	Take() (*model.TUserAddress, error)
	Last() (*model.TUserAddress, error)
	Find() ([]*model.TUserAddress, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUserAddress, err error)
	FindInBatches(result *[]*model.TUserAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TUserAddress) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITUserAddressDo
	Assign(attrs ...field.AssignExpr) ITUserAddressDo
	Joins(fields ...field.RelationField) ITUserAddressDo
	Preload(fields ...field.RelationField) ITUserAddressDo
	FirstOrInit() (*model.TUserAddress, error)
	FirstOrCreate() (*model.TUserAddress, error)
	FindByPage(offset int, limit int) (result []*model.TUserAddress, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITUserAddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tUserAddressDo) Debug() ITUserAddressDo {
	return t.withDO(t.DO.Debug())
}

func (t tUserAddressDo) WithContext(ctx context.Context) ITUserAddressDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tUserAddressDo) ReadDB() ITUserAddressDo {
	return t.Clauses(dbresolver.Read)
}

func (t tUserAddressDo) WriteDB() ITUserAddressDo {
	return t.Clauses(dbresolver.Write)
}

func (t tUserAddressDo) Session(config *gorm.Session) ITUserAddressDo {
	return t.withDO(t.DO.Session(config))
}

func (t tUserAddressDo) Clauses(conds ...clause.Expression) ITUserAddressDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tUserAddressDo) Returning(value interface{}, columns ...string) ITUserAddressDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tUserAddressDo) Not(conds ...gen.Condition) ITUserAddressDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tUserAddressDo) Or(conds ...gen.Condition) ITUserAddressDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tUserAddressDo) Select(conds ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tUserAddressDo) Where(conds ...gen.Condition) ITUserAddressDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tUserAddressDo) Order(conds ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tUserAddressDo) Distinct(cols ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tUserAddressDo) Omit(cols ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tUserAddressDo) Join(table schema.Tabler, on ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tUserAddressDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tUserAddressDo) RightJoin(table schema.Tabler, on ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tUserAddressDo) Group(cols ...field.Expr) ITUserAddressDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tUserAddressDo) Having(conds ...gen.Condition) ITUserAddressDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tUserAddressDo) Limit(limit int) ITUserAddressDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tUserAddressDo) Offset(offset int) ITUserAddressDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tUserAddressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITUserAddressDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tUserAddressDo) Unscoped() ITUserAddressDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tUserAddressDo) Create(values ...*model.TUserAddress) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tUserAddressDo) CreateInBatches(values []*model.TUserAddress, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tUserAddressDo) Save(values ...*model.TUserAddress) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tUserAddressDo) First() (*model.TUserAddress, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAddress), nil
	}
}

func (t tUserAddressDo) Take() (*model.TUserAddress, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAddress), nil
	}
}

func (t tUserAddressDo) Last() (*model.TUserAddress, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAddress), nil
	}
}

func (t tUserAddressDo) Find() ([]*model.TUserAddress, error) {
	result, err := t.DO.Find()
	return result.([]*model.TUserAddress), err
}

func (t tUserAddressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUserAddress, err error) {
	buf := make([]*model.TUserAddress, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tUserAddressDo) FindInBatches(result *[]*model.TUserAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tUserAddressDo) Attrs(attrs ...field.AssignExpr) ITUserAddressDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tUserAddressDo) Assign(attrs ...field.AssignExpr) ITUserAddressDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tUserAddressDo) Joins(fields ...field.RelationField) ITUserAddressDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tUserAddressDo) Preload(fields ...field.RelationField) ITUserAddressDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tUserAddressDo) FirstOrInit() (*model.TUserAddress, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAddress), nil
	}
}

func (t tUserAddressDo) FirstOrCreate() (*model.TUserAddress, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAddress), nil
	}
}

func (t tUserAddressDo) FindByPage(offset int, limit int) (result []*model.TUserAddress, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tUserAddressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tUserAddressDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tUserAddressDo) Delete(models ...*model.TUserAddress) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tUserAddressDo) withDO(do gen.Dao) *tUserAddressDo {
	t.DO = *do.(*gen.DO)
	return t
}
