// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/model"
)

func newTUserAccount(db *gorm.DB, opts ...gen.DOOption) tUserAccount {
	_tUserAccount := tUserAccount{}

	_tUserAccount.tUserAccountDo.UseDB(db, opts...)
	_tUserAccount.tUserAccountDo.UseModel(&model.TUserAccount{})

	tableName := _tUserAccount.tUserAccountDo.TableName()
	_tUserAccount.ALL = field.NewAsterisk(tableName)
	_tUserAccount.ID = field.NewInt64(tableName, "id")
	_tUserAccount.Status = field.NewInt32(tableName, "status")
	_tUserAccount.MainUID = field.NewString(tableName, "main_uid")
	_tUserAccount.MainEmail = field.NewString(tableName, "main_email")
	_tUserAccount.MainProvider = field.NewString(tableName, "main_provider")
	_tUserAccount.AuxUID = field.NewString(tableName, "aux_uid")
	_tUserAccount.AuxProvider = field.NewString(tableName, "aux_provider")
	_tUserAccount.AuxEmail = field.NewString(tableName, "aux_email")
	_tUserAccount.CreateAt = field.NewTime(tableName, "create_at")
	_tUserAccount.UpdateAt = field.NewTime(tableName, "update_at")

	_tUserAccount.fillFieldMap()

	return _tUserAccount
}

type tUserAccount struct {
	tUserAccountDo tUserAccountDo

	ALL          field.Asterisk
	ID           field.Int64
	Status       field.Int32
	MainUID      field.String
	MainEmail    field.String
	MainProvider field.String
	AuxUID       field.String
	AuxProvider  field.String
	AuxEmail     field.String
	CreateAt     field.Time
	UpdateAt     field.Time

	fieldMap map[string]field.Expr
}

func (t tUserAccount) Table(newTableName string) *tUserAccount {
	t.tUserAccountDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tUserAccount) As(alias string) *tUserAccount {
	t.tUserAccountDo.DO = *(t.tUserAccountDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tUserAccount) updateTableName(table string) *tUserAccount {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Status = field.NewInt32(table, "status")
	t.MainUID = field.NewString(table, "main_uid")
	t.MainEmail = field.NewString(table, "main_email")
	t.MainProvider = field.NewString(table, "main_provider")
	t.AuxUID = field.NewString(table, "aux_uid")
	t.AuxProvider = field.NewString(table, "aux_provider")
	t.AuxEmail = field.NewString(table, "aux_email")
	t.CreateAt = field.NewTime(table, "create_at")
	t.UpdateAt = field.NewTime(table, "update_at")

	t.fillFieldMap()

	return t
}

func (t *tUserAccount) WithContext(ctx context.Context) ITUserAccountDo {
	return t.tUserAccountDo.WithContext(ctx)
}

func (t tUserAccount) TableName() string { return t.tUserAccountDo.TableName() }

func (t tUserAccount) Alias() string { return t.tUserAccountDo.Alias() }

func (t tUserAccount) Columns(cols ...field.Expr) gen.Columns {
	return t.tUserAccountDo.Columns(cols...)
}

func (t *tUserAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tUserAccount) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["status"] = t.Status
	t.fieldMap["main_uid"] = t.MainUID
	t.fieldMap["main_email"] = t.MainEmail
	t.fieldMap["main_provider"] = t.MainProvider
	t.fieldMap["aux_uid"] = t.AuxUID
	t.fieldMap["aux_provider"] = t.AuxProvider
	t.fieldMap["aux_email"] = t.AuxEmail
	t.fieldMap["create_at"] = t.CreateAt
	t.fieldMap["update_at"] = t.UpdateAt
}

func (t tUserAccount) clone(db *gorm.DB) tUserAccount {
	t.tUserAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tUserAccount) replaceDB(db *gorm.DB) tUserAccount {
	t.tUserAccountDo.ReplaceDB(db)
	return t
}

type tUserAccountDo struct{ gen.DO }

type ITUserAccountDo interface {
	gen.SubQuery
	Debug() ITUserAccountDo
	WithContext(ctx context.Context) ITUserAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITUserAccountDo
	WriteDB() ITUserAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITUserAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITUserAccountDo
	Not(conds ...gen.Condition) ITUserAccountDo
	Or(conds ...gen.Condition) ITUserAccountDo
	Select(conds ...field.Expr) ITUserAccountDo
	Where(conds ...gen.Condition) ITUserAccountDo
	Order(conds ...field.Expr) ITUserAccountDo
	Distinct(cols ...field.Expr) ITUserAccountDo
	Omit(cols ...field.Expr) ITUserAccountDo
	Join(table schema.Tabler, on ...field.Expr) ITUserAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITUserAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITUserAccountDo
	Group(cols ...field.Expr) ITUserAccountDo
	Having(conds ...gen.Condition) ITUserAccountDo
	Limit(limit int) ITUserAccountDo
	Offset(offset int) ITUserAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITUserAccountDo
	Unscoped() ITUserAccountDo
	Create(values ...*model.TUserAccount) error
	CreateInBatches(values []*model.TUserAccount, batchSize int) error
	Save(values ...*model.TUserAccount) error
	First() (*model.TUserAccount, error)
	Take() (*model.TUserAccount, error)
	Last() (*model.TUserAccount, error)
	Find() ([]*model.TUserAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUserAccount, err error)
	FindInBatches(result *[]*model.TUserAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TUserAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITUserAccountDo
	Assign(attrs ...field.AssignExpr) ITUserAccountDo
	Joins(fields ...field.RelationField) ITUserAccountDo
	Preload(fields ...field.RelationField) ITUserAccountDo
	FirstOrInit() (*model.TUserAccount, error)
	FirstOrCreate() (*model.TUserAccount, error)
	FindByPage(offset int, limit int) (result []*model.TUserAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITUserAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tUserAccountDo) Debug() ITUserAccountDo {
	return t.withDO(t.DO.Debug())
}

func (t tUserAccountDo) WithContext(ctx context.Context) ITUserAccountDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tUserAccountDo) ReadDB() ITUserAccountDo {
	return t.Clauses(dbresolver.Read)
}

func (t tUserAccountDo) WriteDB() ITUserAccountDo {
	return t.Clauses(dbresolver.Write)
}

func (t tUserAccountDo) Session(config *gorm.Session) ITUserAccountDo {
	return t.withDO(t.DO.Session(config))
}

func (t tUserAccountDo) Clauses(conds ...clause.Expression) ITUserAccountDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tUserAccountDo) Returning(value interface{}, columns ...string) ITUserAccountDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tUserAccountDo) Not(conds ...gen.Condition) ITUserAccountDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tUserAccountDo) Or(conds ...gen.Condition) ITUserAccountDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tUserAccountDo) Select(conds ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tUserAccountDo) Where(conds ...gen.Condition) ITUserAccountDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tUserAccountDo) Order(conds ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tUserAccountDo) Distinct(cols ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tUserAccountDo) Omit(cols ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tUserAccountDo) Join(table schema.Tabler, on ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tUserAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tUserAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tUserAccountDo) Group(cols ...field.Expr) ITUserAccountDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tUserAccountDo) Having(conds ...gen.Condition) ITUserAccountDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tUserAccountDo) Limit(limit int) ITUserAccountDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tUserAccountDo) Offset(offset int) ITUserAccountDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tUserAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITUserAccountDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tUserAccountDo) Unscoped() ITUserAccountDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tUserAccountDo) Create(values ...*model.TUserAccount) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tUserAccountDo) CreateInBatches(values []*model.TUserAccount, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tUserAccountDo) Save(values ...*model.TUserAccount) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tUserAccountDo) First() (*model.TUserAccount, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAccount), nil
	}
}

func (t tUserAccountDo) Take() (*model.TUserAccount, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAccount), nil
	}
}

func (t tUserAccountDo) Last() (*model.TUserAccount, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAccount), nil
	}
}

func (t tUserAccountDo) Find() ([]*model.TUserAccount, error) {
	result, err := t.DO.Find()
	return result.([]*model.TUserAccount), err
}

func (t tUserAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUserAccount, err error) {
	buf := make([]*model.TUserAccount, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tUserAccountDo) FindInBatches(result *[]*model.TUserAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tUserAccountDo) Attrs(attrs ...field.AssignExpr) ITUserAccountDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tUserAccountDo) Assign(attrs ...field.AssignExpr) ITUserAccountDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tUserAccountDo) Joins(fields ...field.RelationField) ITUserAccountDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tUserAccountDo) Preload(fields ...field.RelationField) ITUserAccountDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tUserAccountDo) FirstOrInit() (*model.TUserAccount, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAccount), nil
	}
}

func (t tUserAccountDo) FirstOrCreate() (*model.TUserAccount, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserAccount), nil
	}
}

func (t tUserAccountDo) FindByPage(offset int, limit int) (result []*model.TUserAccount, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tUserAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tUserAccountDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tUserAccountDo) Delete(models ...*model.TUserAccount) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tUserAccountDo) withDO(do gen.Dao) *tUserAccountDo {
	t.DO = *do.(*gen.DO)
	return t
}
