// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTDex = "t_dex"

// TDex mapped from table <t_dex>
type TDex struct {
	ID        int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;type:varchar(64);not null" json:"name"`
	Version   string    `gorm:"column:version;type:varchar(64);not null" json:"version"`
	Icon      string    `gorm:"column:icon;type:varchar(2000);not null" json:"icon"`
	Website   string    `gorm:"column:website;type:varchar(2000);not null" json:"website"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TDex's table name
func (*TDex) TableName() string {
	return TableNameTDex
}
