// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTDiscoverApp = "t_discover_app"

// TDiscoverApp mapped from table <t_discover_app>
type TDiscoverApp struct {
	ID          int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(64);not null" json:"name"`
	Version     string    `gorm:"column:version;type:varchar(64);not null" json:"version"`
	Icon        string    `gorm:"column:icon;type:varchar(2000);not null" json:"icon"`
	Website     string    `gorm:"column:website;type:varchar(2000);not null" json:"website"`
	Description string    `gorm:"column:description;type:varchar(1000);not null" json:"description"`
	Disabled    bool      `gorm:"column:disabled;type:tinyint(1);not null" json:"disabled"`
	OrderWeight int32     `gorm:"column:order_weight;type:int;not null;default:1000" json:"order_weight"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TDiscoverApp's table name
func (*TDiscoverApp) TableName() string {
	return TableNameTDiscoverApp
}
