// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameTFamousToken = "t_famous_token"

// TFamousToken mapped from table <t_famous_token>
type TFamousToken struct {
	ID           int32           `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	TokenName    string          `gorm:"column:token_name;type:varchar(128);not null" json:"token_name"`
	ChainName    string          `gorm:"column:chain_name;type:varchar(64);not null" json:"chain_name"`
	TokenAddress string          `gorm:"column:token_address;type:varchar(128);not null" json:"token_address"`
	Decimals     int32           `gorm:"column:decimals;type:int;not null" json:"decimals"`
	IsStable     bool            `gorm:"column:is_stable;type:tinyint(1);not null" json:"is_stable"`
	IsNative     bool            `gorm:"column:is_native;type:tinyint(1);not null" json:"is_native"`
	FullName     string          `gorm:"column:full_name;type:varchar(128);not null" json:"full_name"`
	TotalSupply  decimal.Decimal `gorm:"column:total_supply;type:decimal(64,0);not null;default:0" json:"total_supply"`
	Icon         string          `gorm:"column:icon;type:varchar(1024);not null" json:"icon"`
	Flags        int32           `gorm:"column:flags;type:int;not null" json:"flags"`
	CreatedAt    time.Time       `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time       `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TFamousToken's table name
func (*TFamousToken) TableName() string {
	return TableNameTFamousToken
}
