// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameTPoolDynamic = "t_pool_dynamic"

// TPoolDynamic mapped from table <t_pool_dynamic>
type TPoolDynamic struct {
	ID         int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	ChainID    int64           `gorm:"column:chain_id;type:bigint;not null" json:"chain_id,string"`
	Address    string          `gorm:"column:address;type:varchar(255);not null" json:"address"`
	Liquidity0 decimal.Decimal `gorm:"column:liquidity0;type:decimal(60,0);not null" json:"liquidity0"`
	Liquidity1 decimal.Decimal `gorm:"column:liquidity1;type:decimal(60,0);not null" json:"liquidity1"`
	Liquidityu float64         `gorm:"column:liquidityu;type:double;not null" json:"liquidityu"`
	Block      int64           `gorm:"column:block;type:bigint;not null" json:"block,string"`
	UpdatedAt  time.Time       `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TPoolDynamic's table name
func (*TPoolDynamic) TableName() string {
	return TableNameTPoolDynamic
}
