// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTPool = "t_pool"

// TPool mapped from table <t_pool>
type TPool struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	Address         string    `gorm:"column:address;type:varchar(255);not null" json:"address"`
	ChainID         int64     `gorm:"column:chain_id;type:bigint;not null" json:"chain_id,string"`
	PoolTypeID      int32     `gorm:"column:pool_type_id;type:int;not null" json:"pool_type_id"`
	LaunchpadTypeID int32     `gorm:"column:launchpad_type_id;type:int;not null" json:"launchpad_type_id"`
	Token0ID        int64     `gorm:"column:token0_id;type:bigint;not null" json:"token0_id,string"`
	Token1ID        int64     `gorm:"column:token1_id;type:bigint;not null" json:"token1_id,string"`
	FeeBps          int32     `gorm:"column:fee_bps;type:int;not null" json:"fee_bps"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TPool's table name
func (*TPool) TableName() string {
	return TableNameTPool
}
