// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTPoolStatic = "t_pool_static"

// TPoolStatic mapped from table <t_pool_static>
type TPoolStatic struct {
	PoolID      int64     `gorm:"column:pool_id;type:bigint;primaryKey" json:"pool_id,string"`
	DexPoolID   int32     `gorm:"column:dex_pool_id;type:int;not null" json:"dex_pool_id"`
	LaunchpadID int32     `gorm:"column:launchpad_id;type:int;not null" json:"launchpad_id"`
	Token0ID    int64     `gorm:"column:token0_id;type:bigint;not null" json:"token0_id,string"`
	Token1ID    int64     `gorm:"column:token1_id;type:bigint;not null" json:"token1_id,string"`
	FeePpm      int32     `gorm:"column:fee_ppm;type:int;not null" json:"fee_ppm"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TPoolStatic's table name
func (*TPoolStatic) TableName() string {
	return TableNameTPoolStatic
}
