// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTToken = "t_token"

// TToken mapped from table <t_token>
type TToken struct {
	ID      int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	ChainID int64   `gorm:"column:chain_id;type:bigint;not null" json:"chain_id,string"`
	Address string  `gorm:"column:address;type:varchar(255);not null" json:"address"`
	Priceu  float64 `gorm:"column:priceu;type:double" json:"priceu"`
}

// TableName TToken's table name
func (*TToken) TableName() string {
	return TableNameTToken
}
