// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameTTokenStatic = "t_token_static"

// TTokenStatic mapped from table <t_token_static>
type TTokenStatic struct {
	TokenID           int64           `gorm:"column:token_id;type:bigint;primaryKey" json:"token_id,string"`
	Symbol            string          `gorm:"column:symbol;type:varchar(128);not null" json:"symbol"`
	Decimals          int32           `gorm:"column:decimals;type:int;not null" json:"decimals"`
	FullName          string          `gorm:"column:full_name;type:varchar(128);not null" json:"full_name"`
	CirculatingSupply decimal.Decimal `gorm:"column:circulating_supply;type:decimal(60,0);not null;default:0" json:"circulating_supply"`
	TotalSupply       decimal.Decimal `gorm:"column:total_supply;type:decimal(60,0);not null;default:0" json:"total_supply"`
	DiscoverAt        time.Time       `gorm:"column:discover_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"discover_at"`
	Icon              string          `gorm:"column:icon;type:varchar(1024);not null" json:"icon"`
	Twitter           string          `gorm:"column:twitter;type:varchar(1024);not null" json:"twitter"`
	Telegram          string          `gorm:"column:telegram;type:varchar(1024);not null" json:"telegram"`
	Website           string          `gorm:"column:website;type:varchar(1024);not null" json:"website"`
	Discord           string          `gorm:"column:discord;type:varchar(1024);not null" json:"discord"`
	Comment           string          `gorm:"column:comment;type:varchar(2048);not null" json:"comment"`
	Flags             int32           `gorm:"column:flags;type:int;not null" json:"flags"`
	CreatedAt         time.Time       `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdateAt          time.Time       `gorm:"column:update_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
}

// TableName TTokenStatic's table name
func (*TTokenStatic) TableName() string {
	return TableNameTTokenStatic
}
