// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameTToken = "t_token"

// TToken mapped from table <t_token>
type TToken struct {
	ID                int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	UpdateTimestamp   time.Time       `gorm:"column:update_timestamp;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_timestamp"`
	InsertTimestamp   time.Time       `gorm:"column:insert_timestamp;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"insert_timestamp"`
	Symbol            string          `gorm:"column:symbol;type:varchar(128);not null" json:"symbol"`
	ChainID           int64           `gorm:"column:chain_id;type:bigint;not null" json:"chain_id,string"`
	Address           string          `gorm:"column:address;type:varchar(255);not null" json:"address"`
	Decimals          int32           `gorm:"column:decimals;type:int;not null" json:"decimals"`
	FullName          string          `gorm:"column:full_name;type:varchar(128);not null" json:"full_name"`
	TotalSupply       decimal.Decimal `gorm:"column:total_supply;type:decimal(60,0);not null;default:0" json:"total_supply"`
	CirculatingSupply decimal.Decimal `gorm:"column:circulating_supply;type:decimal(60,0);not null;default:0" json:"circulating_supply"`
	DiscoverTimestamp time.Time       `gorm:"column:discover_timestamp;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"discover_timestamp"`
	Icon              string          `gorm:"column:icon;type:varchar(1024);not null" json:"icon"`
	Twitter           string          `gorm:"column:twitter;type:varchar(1024);not null" json:"twitter"`
	Telegram          string          `gorm:"column:telegram;type:varchar(1024);not null" json:"telegram"`
	Website           string          `gorm:"column:website;type:varchar(1024);not null" json:"website"`
	Discord           string          `gorm:"column:discord;type:varchar(1024);not null" json:"discord"`
	Comment           string          `gorm:"column:comment;type:varchar(2048);not null" json:"comment"`
	Flags             int32           `gorm:"column:flags;type:int;not null" json:"flags"`
}

// TableName TToken's table name
func (*TToken) TableName() string {
	return TableNameTToken
}
