// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTUserAccount = "t_user_account"

// TUserAccount mapped from table <t_user_account>
type TUserAccount struct {
	ID       int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Email    string    `gorm:"column:email;type:varchar(255);not null" json:"email"`
	Status   int32     `gorm:"column:status;type:int" json:"status"`
	Channel  string    `gorm:"column:channel;type:varchar(255)" json:"channel"`
	Sub      string    `gorm:"column:sub;type:varchar(255)" json:"sub"`
	CreateAt time.Time `gorm:"column:create_at;type:datetime;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;type:datetime;default:CURRENT_TIMESTAMP" json:"update_at"`
}

// TableName TUserAccount's table name
func (*TUserAccount) TableName() string {
	return TableNameTUserAccount
}
