// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	TKline12H *tKline12H
	TKline15M *tKline15M
	TKline1D  *tKline1D
	TKline1H  *tKline1H
	TKline1Mo *tKline1Mo
	TKline1W  *tKline1W
	TKline1Y  *tKline1Y
	TKline30M *tKline30M
	TKline4H  *tKline4H
	TKline5M  *tKline5M
	TTrade    *tTrade
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TKline12H = &Q.TKline12H
	TKline15M = &Q.TKline15M
	TKline1D = &Q.TKline1D
	TKline1H = &Q.TKline1H
	TKline1Mo = &Q.TKline1Mo
	TKline1W = &Q.TKline1W
	TKline1Y = &Q.TKline1Y
	TKline30M = &Q.TKline30M
	TKline4H = &Q.TKline4H
	TKline5M = &Q.TKline5M
	TTrade = &Q.TTrade
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		TKline12H: newTKline12H(db, opts...),
		TKline15M: newTKline15M(db, opts...),
		TKline1D:  newTKline1D(db, opts...),
		TKline1H:  newTKline1H(db, opts...),
		TKline1Mo: newTKline1Mo(db, opts...),
		TKline1W:  newTKline1W(db, opts...),
		TKline1Y:  newTKline1Y(db, opts...),
		TKline30M: newTKline30M(db, opts...),
		TKline4H:  newTKline4H(db, opts...),
		TKline5M:  newTKline5M(db, opts...),
		TTrade:    newTTrade(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TKline12H tKline12H
	TKline15M tKline15M
	TKline1D  tKline1D
	TKline1H  tKline1H
	TKline1Mo tKline1Mo
	TKline1W  tKline1W
	TKline1Y  tKline1Y
	TKline30M tKline30M
	TKline4H  tKline4H
	TKline5M  tKline5M
	TTrade    tTrade
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		TKline12H: q.TKline12H.clone(db),
		TKline15M: q.TKline15M.clone(db),
		TKline1D:  q.TKline1D.clone(db),
		TKline1H:  q.TKline1H.clone(db),
		TKline1Mo: q.TKline1Mo.clone(db),
		TKline1W:  q.TKline1W.clone(db),
		TKline1Y:  q.TKline1Y.clone(db),
		TKline30M: q.TKline30M.clone(db),
		TKline4H:  q.TKline4H.clone(db),
		TKline5M:  q.TKline5M.clone(db),
		TTrade:    q.TTrade.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		TKline12H: q.TKline12H.replaceDB(db),
		TKline15M: q.TKline15M.replaceDB(db),
		TKline1D:  q.TKline1D.replaceDB(db),
		TKline1H:  q.TKline1H.replaceDB(db),
		TKline1Mo: q.TKline1Mo.replaceDB(db),
		TKline1W:  q.TKline1W.replaceDB(db),
		TKline1Y:  q.TKline1Y.replaceDB(db),
		TKline30M: q.TKline30M.replaceDB(db),
		TKline4H:  q.TKline4H.replaceDB(db),
		TKline5M:  q.TKline5M.replaceDB(db),
		TTrade:    q.TTrade.replaceDB(db),
	}
}

type queryCtx struct {
	TKline12H ITKline12HDo
	TKline15M ITKline15MDo
	TKline1D  ITKline1DDo
	TKline1H  ITKline1HDo
	TKline1Mo ITKline1MoDo
	TKline1W  ITKline1WDo
	TKline1Y  ITKline1YDo
	TKline30M ITKline30MDo
	TKline4H  ITKline4HDo
	TKline5M  ITKline5MDo
	TTrade    ITTradeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TKline12H: q.TKline12H.WithContext(ctx),
		TKline15M: q.TKline15M.WithContext(ctx),
		TKline1D:  q.TKline1D.WithContext(ctx),
		TKline1H:  q.TKline1H.WithContext(ctx),
		TKline1Mo: q.TKline1Mo.WithContext(ctx),
		TKline1W:  q.TKline1W.WithContext(ctx),
		TKline1Y:  q.TKline1Y.WithContext(ctx),
		TKline30M: q.TKline30M.WithContext(ctx),
		TKline4H:  q.TKline4H.WithContext(ctx),
		TKline5M:  q.TKline5M.WithContext(ctx),
		TTrade:    q.TTrade.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
