// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline30M(db *gorm.DB, opts ...gen.DOOption) tKline30M {
	_tKline30M := tKline30M{}

	_tKline30M.tKline30MDo.UseDB(db, opts...)
	_tKline30M.tKline30MDo.UseModel(&pmodel.TKline30M{})

	tableName := _tKline30M.tKline30MDo.TableName()
	_tKline30M.ALL = field.NewAsterisk(tableName)
	_tKline30M.Ts = field.NewTime(tableName, "ts")
	_tKline30M.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline30M.Openu = field.NewFloat64(tableName, "openu")
	_tKline30M.Highu = field.NewFloat64(tableName, "highu")
	_tKline30M.Lowu = field.NewFloat64(tableName, "lowu")
	_tKline30M.Closeu = field.NewFloat64(tableName, "closeu")
	_tKline30M.Open01 = field.NewFloat64(tableName, "open01")
	_tKline30M.High01 = field.NewFloat64(tableName, "high01")
	_tKline30M.Low01 = field.NewFloat64(tableName, "low01")
	_tKline30M.Close01 = field.NewFloat64(tableName, "close01")
	_tKline30M.Buy0 = field.NewFloat64(tableName, "buy0")
	_tKline30M.Sell0 = field.NewFloat64(tableName, "sell0")
	_tKline30M.Buy1 = field.NewFloat64(tableName, "buy1")
	_tKline30M.Sell1 = field.NewFloat64(tableName, "sell1")
	_tKline30M.Buyu = field.NewFloat64(tableName, "buyu")
	_tKline30M.Sellu = field.NewFloat64(tableName, "sellu")
	_tKline30M.Buys = field.NewInt64(tableName, "buys")
	_tKline30M.Sells = field.NewInt64(tableName, "sells")

	_tKline30M.fillFieldMap()

	return _tKline30M
}

type tKline30M struct {
	tKline30MDo tKline30MDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Openu   field.Float64
	Highu   field.Float64
	Lowu    field.Float64
	Closeu  field.Float64
	Open01  field.Float64
	High01  field.Float64
	Low01   field.Float64
	Close01 field.Float64
	Buy0    field.Float64
	Sell0   field.Float64
	Buy1    field.Float64
	Sell1   field.Float64
	Buyu    field.Float64
	Sellu   field.Float64
	Buys    field.Int64
	Sells   field.Int64

	fieldMap map[string]field.Expr
}

func (t tKline30M) Table(newTableName string) *tKline30M {
	t.tKline30MDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline30M) As(alias string) *tKline30M {
	t.tKline30MDo.DO = *(t.tKline30MDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline30M) updateTableName(table string) *tKline30M {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Openu = field.NewFloat64(table, "openu")
	t.Highu = field.NewFloat64(table, "highu")
	t.Lowu = field.NewFloat64(table, "lowu")
	t.Closeu = field.NewFloat64(table, "closeu")
	t.Open01 = field.NewFloat64(table, "open01")
	t.High01 = field.NewFloat64(table, "high01")
	t.Low01 = field.NewFloat64(table, "low01")
	t.Close01 = field.NewFloat64(table, "close01")
	t.Buy0 = field.NewFloat64(table, "buy0")
	t.Sell0 = field.NewFloat64(table, "sell0")
	t.Buy1 = field.NewFloat64(table, "buy1")
	t.Sell1 = field.NewFloat64(table, "sell1")
	t.Buyu = field.NewFloat64(table, "buyu")
	t.Sellu = field.NewFloat64(table, "sellu")
	t.Buys = field.NewInt64(table, "buys")
	t.Sells = field.NewInt64(table, "sells")

	t.fillFieldMap()

	return t
}

func (t *tKline30M) WithContext(ctx context.Context) ITKline30MDo {
	return t.tKline30MDo.WithContext(ctx)
}

func (t tKline30M) TableName() string { return t.tKline30MDo.TableName() }

func (t tKline30M) Alias() string { return t.tKline30MDo.Alias() }

func (t tKline30M) Columns(cols ...field.Expr) gen.Columns { return t.tKline30MDo.Columns(cols...) }

func (t *tKline30M) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline30M) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 18)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["openu"] = t.Openu
	t.fieldMap["highu"] = t.Highu
	t.fieldMap["lowu"] = t.Lowu
	t.fieldMap["closeu"] = t.Closeu
	t.fieldMap["open01"] = t.Open01
	t.fieldMap["high01"] = t.High01
	t.fieldMap["low01"] = t.Low01
	t.fieldMap["close01"] = t.Close01
	t.fieldMap["buy0"] = t.Buy0
	t.fieldMap["sell0"] = t.Sell0
	t.fieldMap["buy1"] = t.Buy1
	t.fieldMap["sell1"] = t.Sell1
	t.fieldMap["buyu"] = t.Buyu
	t.fieldMap["sellu"] = t.Sellu
	t.fieldMap["buys"] = t.Buys
	t.fieldMap["sells"] = t.Sells
}

func (t tKline30M) clone(db *gorm.DB) tKline30M {
	t.tKline30MDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline30M) replaceDB(db *gorm.DB) tKline30M {
	t.tKline30MDo.ReplaceDB(db)
	return t
}

type tKline30MDo struct{ gen.DO }

type ITKline30MDo interface {
	gen.SubQuery
	Debug() ITKline30MDo
	WithContext(ctx context.Context) ITKline30MDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline30MDo
	WriteDB() ITKline30MDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline30MDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline30MDo
	Not(conds ...gen.Condition) ITKline30MDo
	Or(conds ...gen.Condition) ITKline30MDo
	Select(conds ...field.Expr) ITKline30MDo
	Where(conds ...gen.Condition) ITKline30MDo
	Order(conds ...field.Expr) ITKline30MDo
	Distinct(cols ...field.Expr) ITKline30MDo
	Omit(cols ...field.Expr) ITKline30MDo
	Join(table schema.Tabler, on ...field.Expr) ITKline30MDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline30MDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline30MDo
	Group(cols ...field.Expr) ITKline30MDo
	Having(conds ...gen.Condition) ITKline30MDo
	Limit(limit int) ITKline30MDo
	Offset(offset int) ITKline30MDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline30MDo
	Unscoped() ITKline30MDo
	Create(values ...*pmodel.TKline30M) error
	CreateInBatches(values []*pmodel.TKline30M, batchSize int) error
	Save(values ...*pmodel.TKline30M) error
	First() (*pmodel.TKline30M, error)
	Take() (*pmodel.TKline30M, error)
	Last() (*pmodel.TKline30M, error)
	Find() ([]*pmodel.TKline30M, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline30M, err error)
	FindInBatches(result *[]*pmodel.TKline30M, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline30M) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline30MDo
	Assign(attrs ...field.AssignExpr) ITKline30MDo
	Joins(fields ...field.RelationField) ITKline30MDo
	Preload(fields ...field.RelationField) ITKline30MDo
	FirstOrInit() (*pmodel.TKline30M, error)
	FirstOrCreate() (*pmodel.TKline30M, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline30M, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline30MDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline30MDo) Debug() ITKline30MDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline30MDo) WithContext(ctx context.Context) ITKline30MDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline30MDo) ReadDB() ITKline30MDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline30MDo) WriteDB() ITKline30MDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline30MDo) Session(config *gorm.Session) ITKline30MDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline30MDo) Clauses(conds ...clause.Expression) ITKline30MDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline30MDo) Returning(value interface{}, columns ...string) ITKline30MDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline30MDo) Not(conds ...gen.Condition) ITKline30MDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline30MDo) Or(conds ...gen.Condition) ITKline30MDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline30MDo) Select(conds ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline30MDo) Where(conds ...gen.Condition) ITKline30MDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline30MDo) Order(conds ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline30MDo) Distinct(cols ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline30MDo) Omit(cols ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline30MDo) Join(table schema.Tabler, on ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline30MDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline30MDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline30MDo) Group(cols ...field.Expr) ITKline30MDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline30MDo) Having(conds ...gen.Condition) ITKline30MDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline30MDo) Limit(limit int) ITKline30MDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline30MDo) Offset(offset int) ITKline30MDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline30MDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline30MDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline30MDo) Unscoped() ITKline30MDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline30MDo) Create(values ...*pmodel.TKline30M) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline30MDo) CreateInBatches(values []*pmodel.TKline30M, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline30MDo) Save(values ...*pmodel.TKline30M) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline30MDo) First() (*pmodel.TKline30M, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline30M), nil
	}
}

func (t tKline30MDo) Take() (*pmodel.TKline30M, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline30M), nil
	}
}

func (t tKline30MDo) Last() (*pmodel.TKline30M, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline30M), nil
	}
}

func (t tKline30MDo) Find() ([]*pmodel.TKline30M, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline30M), err
}

func (t tKline30MDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline30M, err error) {
	buf := make([]*pmodel.TKline30M, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline30MDo) FindInBatches(result *[]*pmodel.TKline30M, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline30MDo) Attrs(attrs ...field.AssignExpr) ITKline30MDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline30MDo) Assign(attrs ...field.AssignExpr) ITKline30MDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline30MDo) Joins(fields ...field.RelationField) ITKline30MDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline30MDo) Preload(fields ...field.RelationField) ITKline30MDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline30MDo) FirstOrInit() (*pmodel.TKline30M, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline30M), nil
	}
}

func (t tKline30MDo) FirstOrCreate() (*pmodel.TKline30M, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline30M), nil
	}
}

func (t tKline30MDo) FindByPage(offset int, limit int) (result []*pmodel.TKline30M, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline30MDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline30MDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline30MDo) Delete(models ...*pmodel.TKline30M) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline30MDo) withDO(do gen.Dao) *tKline30MDo {
	t.DO = *do.(*gen.DO)
	return t
}
