// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline1Mo(db *gorm.DB, opts ...gen.DOOption) tKline1Mo {
	_tKline1Mo := tKline1Mo{}

	_tKline1Mo.tKline1MoDo.UseDB(db, opts...)
	_tKline1Mo.tKline1MoDo.UseModel(&pmodel.TKline1Mo{})

	tableName := _tKline1Mo.tKline1MoDo.TableName()
	_tKline1Mo.ALL = field.NewAsterisk(tableName)
	_tKline1Mo.Ts = field.NewTime(tableName, "ts")
	_tKline1Mo.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline1Mo.Openu = field.NewFloat64(tableName, "openu")
	_tKline1Mo.Highu = field.NewFloat64(tableName, "highu")
	_tKline1Mo.Lowu = field.NewFloat64(tableName, "lowu")
	_tKline1Mo.Closeu = field.NewFloat64(tableName, "closeu")
	_tKline1Mo.Open01 = field.NewFloat64(tableName, "open01")
	_tKline1Mo.High01 = field.NewFloat64(tableName, "high01")
	_tKline1Mo.Low01 = field.NewFloat64(tableName, "low01")
	_tKline1Mo.Close01 = field.NewFloat64(tableName, "close01")
	_tKline1Mo.Buy0 = field.NewFloat64(tableName, "buy0")
	_tKline1Mo.Sell0 = field.NewFloat64(tableName, "sell0")
	_tKline1Mo.Buy1 = field.NewFloat64(tableName, "buy1")
	_tKline1Mo.Sell1 = field.NewFloat64(tableName, "sell1")
	_tKline1Mo.Buyu = field.NewFloat64(tableName, "buyu")
	_tKline1Mo.Sellu = field.NewFloat64(tableName, "sellu")
	_tKline1Mo.Buys = field.NewInt64(tableName, "buys")
	_tKline1Mo.Sells = field.NewInt64(tableName, "sells")

	_tKline1Mo.fillFieldMap()

	return _tKline1Mo
}

type tKline1Mo struct {
	tKline1MoDo tKline1MoDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Openu   field.Float64
	Highu   field.Float64
	Lowu    field.Float64
	Closeu  field.Float64
	Open01  field.Float64
	High01  field.Float64
	Low01   field.Float64
	Close01 field.Float64
	Buy0    field.Float64
	Sell0   field.Float64
	Buy1    field.Float64
	Sell1   field.Float64
	Buyu    field.Float64
	Sellu   field.Float64
	Buys    field.Int64
	Sells   field.Int64

	fieldMap map[string]field.Expr
}

func (t tKline1Mo) Table(newTableName string) *tKline1Mo {
	t.tKline1MoDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline1Mo) As(alias string) *tKline1Mo {
	t.tKline1MoDo.DO = *(t.tKline1MoDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline1Mo) updateTableName(table string) *tKline1Mo {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Openu = field.NewFloat64(table, "openu")
	t.Highu = field.NewFloat64(table, "highu")
	t.Lowu = field.NewFloat64(table, "lowu")
	t.Closeu = field.NewFloat64(table, "closeu")
	t.Open01 = field.NewFloat64(table, "open01")
	t.High01 = field.NewFloat64(table, "high01")
	t.Low01 = field.NewFloat64(table, "low01")
	t.Close01 = field.NewFloat64(table, "close01")
	t.Buy0 = field.NewFloat64(table, "buy0")
	t.Sell0 = field.NewFloat64(table, "sell0")
	t.Buy1 = field.NewFloat64(table, "buy1")
	t.Sell1 = field.NewFloat64(table, "sell1")
	t.Buyu = field.NewFloat64(table, "buyu")
	t.Sellu = field.NewFloat64(table, "sellu")
	t.Buys = field.NewInt64(table, "buys")
	t.Sells = field.NewInt64(table, "sells")

	t.fillFieldMap()

	return t
}

func (t *tKline1Mo) WithContext(ctx context.Context) ITKline1MoDo {
	return t.tKline1MoDo.WithContext(ctx)
}

func (t tKline1Mo) TableName() string { return t.tKline1MoDo.TableName() }

func (t tKline1Mo) Alias() string { return t.tKline1MoDo.Alias() }

func (t tKline1Mo) Columns(cols ...field.Expr) gen.Columns { return t.tKline1MoDo.Columns(cols...) }

func (t *tKline1Mo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline1Mo) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 18)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["openu"] = t.Openu
	t.fieldMap["highu"] = t.Highu
	t.fieldMap["lowu"] = t.Lowu
	t.fieldMap["closeu"] = t.Closeu
	t.fieldMap["open01"] = t.Open01
	t.fieldMap["high01"] = t.High01
	t.fieldMap["low01"] = t.Low01
	t.fieldMap["close01"] = t.Close01
	t.fieldMap["buy0"] = t.Buy0
	t.fieldMap["sell0"] = t.Sell0
	t.fieldMap["buy1"] = t.Buy1
	t.fieldMap["sell1"] = t.Sell1
	t.fieldMap["buyu"] = t.Buyu
	t.fieldMap["sellu"] = t.Sellu
	t.fieldMap["buys"] = t.Buys
	t.fieldMap["sells"] = t.Sells
}

func (t tKline1Mo) clone(db *gorm.DB) tKline1Mo {
	t.tKline1MoDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline1Mo) replaceDB(db *gorm.DB) tKline1Mo {
	t.tKline1MoDo.ReplaceDB(db)
	return t
}

type tKline1MoDo struct{ gen.DO }

type ITKline1MoDo interface {
	gen.SubQuery
	Debug() ITKline1MoDo
	WithContext(ctx context.Context) ITKline1MoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline1MoDo
	WriteDB() ITKline1MoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline1MoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline1MoDo
	Not(conds ...gen.Condition) ITKline1MoDo
	Or(conds ...gen.Condition) ITKline1MoDo
	Select(conds ...field.Expr) ITKline1MoDo
	Where(conds ...gen.Condition) ITKline1MoDo
	Order(conds ...field.Expr) ITKline1MoDo
	Distinct(cols ...field.Expr) ITKline1MoDo
	Omit(cols ...field.Expr) ITKline1MoDo
	Join(table schema.Tabler, on ...field.Expr) ITKline1MoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1MoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline1MoDo
	Group(cols ...field.Expr) ITKline1MoDo
	Having(conds ...gen.Condition) ITKline1MoDo
	Limit(limit int) ITKline1MoDo
	Offset(offset int) ITKline1MoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1MoDo
	Unscoped() ITKline1MoDo
	Create(values ...*pmodel.TKline1Mo) error
	CreateInBatches(values []*pmodel.TKline1Mo, batchSize int) error
	Save(values ...*pmodel.TKline1Mo) error
	First() (*pmodel.TKline1Mo, error)
	Take() (*pmodel.TKline1Mo, error)
	Last() (*pmodel.TKline1Mo, error)
	Find() ([]*pmodel.TKline1Mo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1Mo, err error)
	FindInBatches(result *[]*pmodel.TKline1Mo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline1Mo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline1MoDo
	Assign(attrs ...field.AssignExpr) ITKline1MoDo
	Joins(fields ...field.RelationField) ITKline1MoDo
	Preload(fields ...field.RelationField) ITKline1MoDo
	FirstOrInit() (*pmodel.TKline1Mo, error)
	FirstOrCreate() (*pmodel.TKline1Mo, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline1Mo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline1MoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline1MoDo) Debug() ITKline1MoDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline1MoDo) WithContext(ctx context.Context) ITKline1MoDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline1MoDo) ReadDB() ITKline1MoDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline1MoDo) WriteDB() ITKline1MoDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline1MoDo) Session(config *gorm.Session) ITKline1MoDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline1MoDo) Clauses(conds ...clause.Expression) ITKline1MoDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline1MoDo) Returning(value interface{}, columns ...string) ITKline1MoDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline1MoDo) Not(conds ...gen.Condition) ITKline1MoDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline1MoDo) Or(conds ...gen.Condition) ITKline1MoDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline1MoDo) Select(conds ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline1MoDo) Where(conds ...gen.Condition) ITKline1MoDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline1MoDo) Order(conds ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline1MoDo) Distinct(cols ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline1MoDo) Omit(cols ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline1MoDo) Join(table schema.Tabler, on ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline1MoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline1MoDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline1MoDo) Group(cols ...field.Expr) ITKline1MoDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline1MoDo) Having(conds ...gen.Condition) ITKline1MoDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline1MoDo) Limit(limit int) ITKline1MoDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline1MoDo) Offset(offset int) ITKline1MoDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline1MoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1MoDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline1MoDo) Unscoped() ITKline1MoDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline1MoDo) Create(values ...*pmodel.TKline1Mo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline1MoDo) CreateInBatches(values []*pmodel.TKline1Mo, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline1MoDo) Save(values ...*pmodel.TKline1Mo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline1MoDo) First() (*pmodel.TKline1Mo, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Mo), nil
	}
}

func (t tKline1MoDo) Take() (*pmodel.TKline1Mo, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Mo), nil
	}
}

func (t tKline1MoDo) Last() (*pmodel.TKline1Mo, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Mo), nil
	}
}

func (t tKline1MoDo) Find() ([]*pmodel.TKline1Mo, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline1Mo), err
}

func (t tKline1MoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1Mo, err error) {
	buf := make([]*pmodel.TKline1Mo, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline1MoDo) FindInBatches(result *[]*pmodel.TKline1Mo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline1MoDo) Attrs(attrs ...field.AssignExpr) ITKline1MoDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline1MoDo) Assign(attrs ...field.AssignExpr) ITKline1MoDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline1MoDo) Joins(fields ...field.RelationField) ITKline1MoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline1MoDo) Preload(fields ...field.RelationField) ITKline1MoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline1MoDo) FirstOrInit() (*pmodel.TKline1Mo, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Mo), nil
	}
}

func (t tKline1MoDo) FirstOrCreate() (*pmodel.TKline1Mo, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Mo), nil
	}
}

func (t tKline1MoDo) FindByPage(offset int, limit int) (result []*pmodel.TKline1Mo, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline1MoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline1MoDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline1MoDo) Delete(models ...*pmodel.TKline1Mo) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline1MoDo) withDO(do gen.Dao) *tKline1MoDo {
	t.DO = *do.(*gen.DO)
	return t
}
