// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline1Y(db *gorm.DB, opts ...gen.DOOption) tKline1Y {
	_tKline1Y := tKline1Y{}

	_tKline1Y.tKline1YDo.UseDB(db, opts...)
	_tKline1Y.tKline1YDo.UseModel(&pmodel.TKline1Y{})

	tableName := _tKline1Y.tKline1YDo.TableName()
	_tKline1Y.ALL = field.NewAsterisk(tableName)
	_tKline1Y.Ts = field.NewTime(tableName, "ts")
	_tKline1Y.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline1Y.Open = field.NewFloat64(tableName, "open")
	_tKline1Y.High = field.NewFloat64(tableName, "high")
	_tKline1Y.Low = field.NewFloat64(tableName, "low")
	_tKline1Y.Close = field.NewFloat64(tableName, "close")
	_tKline1Y.Volume0 = field.NewFloat64(tableName, "volume0")
	_tKline1Y.Volume1 = field.NewFloat64(tableName, "volume1")
	_tKline1Y.Volume = field.NewFloat64(tableName, "volume")

	_tKline1Y.fillFieldMap()

	return _tKline1Y
}

type tKline1Y struct {
	tKline1YDo tKline1YDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Open    field.Float64
	High    field.Float64
	Low     field.Float64
	Close   field.Float64
	Volume0 field.Float64
	Volume1 field.Float64
	Volume  field.Float64

	fieldMap map[string]field.Expr
}

func (t tKline1Y) Table(newTableName string) *tKline1Y {
	t.tKline1YDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline1Y) As(alias string) *tKline1Y {
	t.tKline1YDo.DO = *(t.tKline1YDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline1Y) updateTableName(table string) *tKline1Y {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Open = field.NewFloat64(table, "open")
	t.High = field.NewFloat64(table, "high")
	t.Low = field.NewFloat64(table, "low")
	t.Close = field.NewFloat64(table, "close")
	t.Volume0 = field.NewFloat64(table, "volume0")
	t.Volume1 = field.NewFloat64(table, "volume1")
	t.Volume = field.NewFloat64(table, "volume")

	t.fillFieldMap()

	return t
}

func (t *tKline1Y) WithContext(ctx context.Context) ITKline1YDo { return t.tKline1YDo.WithContext(ctx) }

func (t tKline1Y) TableName() string { return t.tKline1YDo.TableName() }

func (t tKline1Y) Alias() string { return t.tKline1YDo.Alias() }

func (t tKline1Y) Columns(cols ...field.Expr) gen.Columns { return t.tKline1YDo.Columns(cols...) }

func (t *tKline1Y) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline1Y) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["open"] = t.Open
	t.fieldMap["high"] = t.High
	t.fieldMap["low"] = t.Low
	t.fieldMap["close"] = t.Close
	t.fieldMap["volume0"] = t.Volume0
	t.fieldMap["volume1"] = t.Volume1
	t.fieldMap["volume"] = t.Volume
}

func (t tKline1Y) clone(db *gorm.DB) tKline1Y {
	t.tKline1YDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline1Y) replaceDB(db *gorm.DB) tKline1Y {
	t.tKline1YDo.ReplaceDB(db)
	return t
}

type tKline1YDo struct{ gen.DO }

type ITKline1YDo interface {
	gen.SubQuery
	Debug() ITKline1YDo
	WithContext(ctx context.Context) ITKline1YDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline1YDo
	WriteDB() ITKline1YDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline1YDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline1YDo
	Not(conds ...gen.Condition) ITKline1YDo
	Or(conds ...gen.Condition) ITKline1YDo
	Select(conds ...field.Expr) ITKline1YDo
	Where(conds ...gen.Condition) ITKline1YDo
	Order(conds ...field.Expr) ITKline1YDo
	Distinct(cols ...field.Expr) ITKline1YDo
	Omit(cols ...field.Expr) ITKline1YDo
	Join(table schema.Tabler, on ...field.Expr) ITKline1YDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1YDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline1YDo
	Group(cols ...field.Expr) ITKline1YDo
	Having(conds ...gen.Condition) ITKline1YDo
	Limit(limit int) ITKline1YDo
	Offset(offset int) ITKline1YDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1YDo
	Unscoped() ITKline1YDo
	Create(values ...*pmodel.TKline1Y) error
	CreateInBatches(values []*pmodel.TKline1Y, batchSize int) error
	Save(values ...*pmodel.TKline1Y) error
	First() (*pmodel.TKline1Y, error)
	Take() (*pmodel.TKline1Y, error)
	Last() (*pmodel.TKline1Y, error)
	Find() ([]*pmodel.TKline1Y, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1Y, err error)
	FindInBatches(result *[]*pmodel.TKline1Y, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline1Y) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline1YDo
	Assign(attrs ...field.AssignExpr) ITKline1YDo
	Joins(fields ...field.RelationField) ITKline1YDo
	Preload(fields ...field.RelationField) ITKline1YDo
	FirstOrInit() (*pmodel.TKline1Y, error)
	FirstOrCreate() (*pmodel.TKline1Y, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline1Y, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline1YDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline1YDo) Debug() ITKline1YDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline1YDo) WithContext(ctx context.Context) ITKline1YDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline1YDo) ReadDB() ITKline1YDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline1YDo) WriteDB() ITKline1YDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline1YDo) Session(config *gorm.Session) ITKline1YDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline1YDo) Clauses(conds ...clause.Expression) ITKline1YDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline1YDo) Returning(value interface{}, columns ...string) ITKline1YDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline1YDo) Not(conds ...gen.Condition) ITKline1YDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline1YDo) Or(conds ...gen.Condition) ITKline1YDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline1YDo) Select(conds ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline1YDo) Where(conds ...gen.Condition) ITKline1YDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline1YDo) Order(conds ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline1YDo) Distinct(cols ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline1YDo) Omit(cols ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline1YDo) Join(table schema.Tabler, on ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline1YDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline1YDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline1YDo) Group(cols ...field.Expr) ITKline1YDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline1YDo) Having(conds ...gen.Condition) ITKline1YDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline1YDo) Limit(limit int) ITKline1YDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline1YDo) Offset(offset int) ITKline1YDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline1YDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1YDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline1YDo) Unscoped() ITKline1YDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline1YDo) Create(values ...*pmodel.TKline1Y) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline1YDo) CreateInBatches(values []*pmodel.TKline1Y, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline1YDo) Save(values ...*pmodel.TKline1Y) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline1YDo) First() (*pmodel.TKline1Y, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Y), nil
	}
}

func (t tKline1YDo) Take() (*pmodel.TKline1Y, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Y), nil
	}
}

func (t tKline1YDo) Last() (*pmodel.TKline1Y, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Y), nil
	}
}

func (t tKline1YDo) Find() ([]*pmodel.TKline1Y, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline1Y), err
}

func (t tKline1YDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1Y, err error) {
	buf := make([]*pmodel.TKline1Y, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline1YDo) FindInBatches(result *[]*pmodel.TKline1Y, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline1YDo) Attrs(attrs ...field.AssignExpr) ITKline1YDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline1YDo) Assign(attrs ...field.AssignExpr) ITKline1YDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline1YDo) Joins(fields ...field.RelationField) ITKline1YDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline1YDo) Preload(fields ...field.RelationField) ITKline1YDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline1YDo) FirstOrInit() (*pmodel.TKline1Y, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Y), nil
	}
}

func (t tKline1YDo) FirstOrCreate() (*pmodel.TKline1Y, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1Y), nil
	}
}

func (t tKline1YDo) FindByPage(offset int, limit int) (result []*pmodel.TKline1Y, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline1YDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline1YDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline1YDo) Delete(models ...*pmodel.TKline1Y) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline1YDo) withDO(do gen.Dao) *tKline1YDo {
	t.DO = *do.(*gen.DO)
	return t
}
