// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline1D(db *gorm.DB, opts ...gen.DOOption) tKline1D {
	_tKline1D := tKline1D{}

	_tKline1D.tKline1DDo.UseDB(db, opts...)
	_tKline1D.tKline1DDo.UseModel(&pmodel.TKline1D{})

	tableName := _tKline1D.tKline1DDo.TableName()
	_tKline1D.ALL = field.NewAsterisk(tableName)
	_tKline1D.Ts = field.NewTime(tableName, "ts")
	_tKline1D.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline1D.Openu = field.NewFloat64(tableName, "openu")
	_tKline1D.Highu = field.NewFloat64(tableName, "highu")
	_tKline1D.Lowu = field.NewFloat64(tableName, "lowu")
	_tKline1D.Closeu = field.NewFloat64(tableName, "closeu")
	_tKline1D.Open01 = field.NewFloat64(tableName, "open01")
	_tKline1D.High01 = field.NewFloat64(tableName, "high01")
	_tKline1D.Low01 = field.NewFloat64(tableName, "low01")
	_tKline1D.Close01 = field.NewFloat64(tableName, "close01")
	_tKline1D.Buy0 = field.NewFloat64(tableName, "buy0")
	_tKline1D.Sell0 = field.NewFloat64(tableName, "sell0")
	_tKline1D.Buy1 = field.NewFloat64(tableName, "buy1")
	_tKline1D.Sell1 = field.NewFloat64(tableName, "sell1")
	_tKline1D.Buyu = field.NewFloat64(tableName, "buyu")
	_tKline1D.Sellu = field.NewFloat64(tableName, "sellu")
	_tKline1D.Buys = field.NewInt64(tableName, "buys")
	_tKline1D.Sells = field.NewInt64(tableName, "sells")

	_tKline1D.fillFieldMap()

	return _tKline1D
}

type tKline1D struct {
	tKline1DDo tKline1DDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Openu   field.Float64
	Highu   field.Float64
	Lowu    field.Float64
	Closeu  field.Float64
	Open01  field.Float64
	High01  field.Float64
	Low01   field.Float64
	Close01 field.Float64
	Buy0    field.Float64
	Sell0   field.Float64
	Buy1    field.Float64
	Sell1   field.Float64
	Buyu    field.Float64
	Sellu   field.Float64
	Buys    field.Int64
	Sells   field.Int64

	fieldMap map[string]field.Expr
}

func (t tKline1D) Table(newTableName string) *tKline1D {
	t.tKline1DDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline1D) As(alias string) *tKline1D {
	t.tKline1DDo.DO = *(t.tKline1DDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline1D) updateTableName(table string) *tKline1D {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Openu = field.NewFloat64(table, "openu")
	t.Highu = field.NewFloat64(table, "highu")
	t.Lowu = field.NewFloat64(table, "lowu")
	t.Closeu = field.NewFloat64(table, "closeu")
	t.Open01 = field.NewFloat64(table, "open01")
	t.High01 = field.NewFloat64(table, "high01")
	t.Low01 = field.NewFloat64(table, "low01")
	t.Close01 = field.NewFloat64(table, "close01")
	t.Buy0 = field.NewFloat64(table, "buy0")
	t.Sell0 = field.NewFloat64(table, "sell0")
	t.Buy1 = field.NewFloat64(table, "buy1")
	t.Sell1 = field.NewFloat64(table, "sell1")
	t.Buyu = field.NewFloat64(table, "buyu")
	t.Sellu = field.NewFloat64(table, "sellu")
	t.Buys = field.NewInt64(table, "buys")
	t.Sells = field.NewInt64(table, "sells")

	t.fillFieldMap()

	return t
}

func (t *tKline1D) WithContext(ctx context.Context) ITKline1DDo { return t.tKline1DDo.WithContext(ctx) }

func (t tKline1D) TableName() string { return t.tKline1DDo.TableName() }

func (t tKline1D) Alias() string { return t.tKline1DDo.Alias() }

func (t tKline1D) Columns(cols ...field.Expr) gen.Columns { return t.tKline1DDo.Columns(cols...) }

func (t *tKline1D) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline1D) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 18)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["openu"] = t.Openu
	t.fieldMap["highu"] = t.Highu
	t.fieldMap["lowu"] = t.Lowu
	t.fieldMap["closeu"] = t.Closeu
	t.fieldMap["open01"] = t.Open01
	t.fieldMap["high01"] = t.High01
	t.fieldMap["low01"] = t.Low01
	t.fieldMap["close01"] = t.Close01
	t.fieldMap["buy0"] = t.Buy0
	t.fieldMap["sell0"] = t.Sell0
	t.fieldMap["buy1"] = t.Buy1
	t.fieldMap["sell1"] = t.Sell1
	t.fieldMap["buyu"] = t.Buyu
	t.fieldMap["sellu"] = t.Sellu
	t.fieldMap["buys"] = t.Buys
	t.fieldMap["sells"] = t.Sells
}

func (t tKline1D) clone(db *gorm.DB) tKline1D {
	t.tKline1DDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline1D) replaceDB(db *gorm.DB) tKline1D {
	t.tKline1DDo.ReplaceDB(db)
	return t
}

type tKline1DDo struct{ gen.DO }

type ITKline1DDo interface {
	gen.SubQuery
	Debug() ITKline1DDo
	WithContext(ctx context.Context) ITKline1DDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline1DDo
	WriteDB() ITKline1DDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline1DDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline1DDo
	Not(conds ...gen.Condition) ITKline1DDo
	Or(conds ...gen.Condition) ITKline1DDo
	Select(conds ...field.Expr) ITKline1DDo
	Where(conds ...gen.Condition) ITKline1DDo
	Order(conds ...field.Expr) ITKline1DDo
	Distinct(cols ...field.Expr) ITKline1DDo
	Omit(cols ...field.Expr) ITKline1DDo
	Join(table schema.Tabler, on ...field.Expr) ITKline1DDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1DDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline1DDo
	Group(cols ...field.Expr) ITKline1DDo
	Having(conds ...gen.Condition) ITKline1DDo
	Limit(limit int) ITKline1DDo
	Offset(offset int) ITKline1DDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1DDo
	Unscoped() ITKline1DDo
	Create(values ...*pmodel.TKline1D) error
	CreateInBatches(values []*pmodel.TKline1D, batchSize int) error
	Save(values ...*pmodel.TKline1D) error
	First() (*pmodel.TKline1D, error)
	Take() (*pmodel.TKline1D, error)
	Last() (*pmodel.TKline1D, error)
	Find() ([]*pmodel.TKline1D, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1D, err error)
	FindInBatches(result *[]*pmodel.TKline1D, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline1D) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline1DDo
	Assign(attrs ...field.AssignExpr) ITKline1DDo
	Joins(fields ...field.RelationField) ITKline1DDo
	Preload(fields ...field.RelationField) ITKline1DDo
	FirstOrInit() (*pmodel.TKline1D, error)
	FirstOrCreate() (*pmodel.TKline1D, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline1D, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline1DDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline1DDo) Debug() ITKline1DDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline1DDo) WithContext(ctx context.Context) ITKline1DDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline1DDo) ReadDB() ITKline1DDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline1DDo) WriteDB() ITKline1DDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline1DDo) Session(config *gorm.Session) ITKline1DDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline1DDo) Clauses(conds ...clause.Expression) ITKline1DDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline1DDo) Returning(value interface{}, columns ...string) ITKline1DDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline1DDo) Not(conds ...gen.Condition) ITKline1DDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline1DDo) Or(conds ...gen.Condition) ITKline1DDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline1DDo) Select(conds ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline1DDo) Where(conds ...gen.Condition) ITKline1DDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline1DDo) Order(conds ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline1DDo) Distinct(cols ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline1DDo) Omit(cols ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline1DDo) Join(table schema.Tabler, on ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline1DDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline1DDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline1DDo) Group(cols ...field.Expr) ITKline1DDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline1DDo) Having(conds ...gen.Condition) ITKline1DDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline1DDo) Limit(limit int) ITKline1DDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline1DDo) Offset(offset int) ITKline1DDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline1DDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1DDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline1DDo) Unscoped() ITKline1DDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline1DDo) Create(values ...*pmodel.TKline1D) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline1DDo) CreateInBatches(values []*pmodel.TKline1D, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline1DDo) Save(values ...*pmodel.TKline1D) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline1DDo) First() (*pmodel.TKline1D, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1D), nil
	}
}

func (t tKline1DDo) Take() (*pmodel.TKline1D, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1D), nil
	}
}

func (t tKline1DDo) Last() (*pmodel.TKline1D, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1D), nil
	}
}

func (t tKline1DDo) Find() ([]*pmodel.TKline1D, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline1D), err
}

func (t tKline1DDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1D, err error) {
	buf := make([]*pmodel.TKline1D, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline1DDo) FindInBatches(result *[]*pmodel.TKline1D, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline1DDo) Attrs(attrs ...field.AssignExpr) ITKline1DDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline1DDo) Assign(attrs ...field.AssignExpr) ITKline1DDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline1DDo) Joins(fields ...field.RelationField) ITKline1DDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline1DDo) Preload(fields ...field.RelationField) ITKline1DDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline1DDo) FirstOrInit() (*pmodel.TKline1D, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1D), nil
	}
}

func (t tKline1DDo) FirstOrCreate() (*pmodel.TKline1D, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1D), nil
	}
}

func (t tKline1DDo) FindByPage(offset int, limit int) (result []*pmodel.TKline1D, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline1DDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline1DDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline1DDo) Delete(models ...*pmodel.TKline1D) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline1DDo) withDO(do gen.Dao) *tKline1DDo {
	t.DO = *do.(*gen.DO)
	return t
}
