// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline12H(db *gorm.DB, opts ...gen.DOOption) tKline12H {
	_tKline12H := tKline12H{}

	_tKline12H.tKline12HDo.UseDB(db, opts...)
	_tKline12H.tKline12HDo.UseModel(&pmodel.TKline12H{})

	tableName := _tKline12H.tKline12HDo.TableName()
	_tKline12H.ALL = field.NewAsterisk(tableName)
	_tKline12H.Ts = field.NewTime(tableName, "ts")
	_tKline12H.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline12H.Openu = field.NewFloat64(tableName, "openu")
	_tKline12H.Highu = field.NewFloat64(tableName, "highu")
	_tKline12H.Lowu = field.NewFloat64(tableName, "lowu")
	_tKline12H.Closeu = field.NewFloat64(tableName, "closeu")
	_tKline12H.Open01 = field.NewFloat64(tableName, "open01")
	_tKline12H.High01 = field.NewFloat64(tableName, "high01")
	_tKline12H.Low01 = field.NewFloat64(tableName, "low01")
	_tKline12H.Close01 = field.NewFloat64(tableName, "close01")
	_tKline12H.Buy0 = field.NewFloat64(tableName, "buy0")
	_tKline12H.Sell0 = field.NewFloat64(tableName, "sell0")
	_tKline12H.Buy1 = field.NewFloat64(tableName, "buy1")
	_tKline12H.Sell1 = field.NewFloat64(tableName, "sell1")
	_tKline12H.Buyu = field.NewFloat64(tableName, "buyu")
	_tKline12H.Sellu = field.NewFloat64(tableName, "sellu")
	_tKline12H.Buys = field.NewInt64(tableName, "buys")
	_tKline12H.Sells = field.NewInt64(tableName, "sells")

	_tKline12H.fillFieldMap()

	return _tKline12H
}

type tKline12H struct {
	tKline12HDo tKline12HDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Openu   field.Float64
	Highu   field.Float64
	Lowu    field.Float64
	Closeu  field.Float64
	Open01  field.Float64
	High01  field.Float64
	Low01   field.Float64
	Close01 field.Float64
	Buy0    field.Float64
	Sell0   field.Float64
	Buy1    field.Float64
	Sell1   field.Float64
	Buyu    field.Float64
	Sellu   field.Float64
	Buys    field.Int64
	Sells   field.Int64

	fieldMap map[string]field.Expr
}

func (t tKline12H) Table(newTableName string) *tKline12H {
	t.tKline12HDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline12H) As(alias string) *tKline12H {
	t.tKline12HDo.DO = *(t.tKline12HDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline12H) updateTableName(table string) *tKline12H {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Openu = field.NewFloat64(table, "openu")
	t.Highu = field.NewFloat64(table, "highu")
	t.Lowu = field.NewFloat64(table, "lowu")
	t.Closeu = field.NewFloat64(table, "closeu")
	t.Open01 = field.NewFloat64(table, "open01")
	t.High01 = field.NewFloat64(table, "high01")
	t.Low01 = field.NewFloat64(table, "low01")
	t.Close01 = field.NewFloat64(table, "close01")
	t.Buy0 = field.NewFloat64(table, "buy0")
	t.Sell0 = field.NewFloat64(table, "sell0")
	t.Buy1 = field.NewFloat64(table, "buy1")
	t.Sell1 = field.NewFloat64(table, "sell1")
	t.Buyu = field.NewFloat64(table, "buyu")
	t.Sellu = field.NewFloat64(table, "sellu")
	t.Buys = field.NewInt64(table, "buys")
	t.Sells = field.NewInt64(table, "sells")

	t.fillFieldMap()

	return t
}

func (t *tKline12H) WithContext(ctx context.Context) ITKline12HDo {
	return t.tKline12HDo.WithContext(ctx)
}

func (t tKline12H) TableName() string { return t.tKline12HDo.TableName() }

func (t tKline12H) Alias() string { return t.tKline12HDo.Alias() }

func (t tKline12H) Columns(cols ...field.Expr) gen.Columns { return t.tKline12HDo.Columns(cols...) }

func (t *tKline12H) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline12H) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 18)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["openu"] = t.Openu
	t.fieldMap["highu"] = t.Highu
	t.fieldMap["lowu"] = t.Lowu
	t.fieldMap["closeu"] = t.Closeu
	t.fieldMap["open01"] = t.Open01
	t.fieldMap["high01"] = t.High01
	t.fieldMap["low01"] = t.Low01
	t.fieldMap["close01"] = t.Close01
	t.fieldMap["buy0"] = t.Buy0
	t.fieldMap["sell0"] = t.Sell0
	t.fieldMap["buy1"] = t.Buy1
	t.fieldMap["sell1"] = t.Sell1
	t.fieldMap["buyu"] = t.Buyu
	t.fieldMap["sellu"] = t.Sellu
	t.fieldMap["buys"] = t.Buys
	t.fieldMap["sells"] = t.Sells
}

func (t tKline12H) clone(db *gorm.DB) tKline12H {
	t.tKline12HDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline12H) replaceDB(db *gorm.DB) tKline12H {
	t.tKline12HDo.ReplaceDB(db)
	return t
}

type tKline12HDo struct{ gen.DO }

type ITKline12HDo interface {
	gen.SubQuery
	Debug() ITKline12HDo
	WithContext(ctx context.Context) ITKline12HDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline12HDo
	WriteDB() ITKline12HDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline12HDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline12HDo
	Not(conds ...gen.Condition) ITKline12HDo
	Or(conds ...gen.Condition) ITKline12HDo
	Select(conds ...field.Expr) ITKline12HDo
	Where(conds ...gen.Condition) ITKline12HDo
	Order(conds ...field.Expr) ITKline12HDo
	Distinct(cols ...field.Expr) ITKline12HDo
	Omit(cols ...field.Expr) ITKline12HDo
	Join(table schema.Tabler, on ...field.Expr) ITKline12HDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline12HDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline12HDo
	Group(cols ...field.Expr) ITKline12HDo
	Having(conds ...gen.Condition) ITKline12HDo
	Limit(limit int) ITKline12HDo
	Offset(offset int) ITKline12HDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline12HDo
	Unscoped() ITKline12HDo
	Create(values ...*pmodel.TKline12H) error
	CreateInBatches(values []*pmodel.TKline12H, batchSize int) error
	Save(values ...*pmodel.TKline12H) error
	First() (*pmodel.TKline12H, error)
	Take() (*pmodel.TKline12H, error)
	Last() (*pmodel.TKline12H, error)
	Find() ([]*pmodel.TKline12H, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline12H, err error)
	FindInBatches(result *[]*pmodel.TKline12H, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline12H) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline12HDo
	Assign(attrs ...field.AssignExpr) ITKline12HDo
	Joins(fields ...field.RelationField) ITKline12HDo
	Preload(fields ...field.RelationField) ITKline12HDo
	FirstOrInit() (*pmodel.TKline12H, error)
	FirstOrCreate() (*pmodel.TKline12H, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline12H, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline12HDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline12HDo) Debug() ITKline12HDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline12HDo) WithContext(ctx context.Context) ITKline12HDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline12HDo) ReadDB() ITKline12HDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline12HDo) WriteDB() ITKline12HDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline12HDo) Session(config *gorm.Session) ITKline12HDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline12HDo) Clauses(conds ...clause.Expression) ITKline12HDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline12HDo) Returning(value interface{}, columns ...string) ITKline12HDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline12HDo) Not(conds ...gen.Condition) ITKline12HDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline12HDo) Or(conds ...gen.Condition) ITKline12HDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline12HDo) Select(conds ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline12HDo) Where(conds ...gen.Condition) ITKline12HDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline12HDo) Order(conds ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline12HDo) Distinct(cols ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline12HDo) Omit(cols ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline12HDo) Join(table schema.Tabler, on ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline12HDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline12HDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline12HDo) Group(cols ...field.Expr) ITKline12HDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline12HDo) Having(conds ...gen.Condition) ITKline12HDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline12HDo) Limit(limit int) ITKline12HDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline12HDo) Offset(offset int) ITKline12HDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline12HDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline12HDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline12HDo) Unscoped() ITKline12HDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline12HDo) Create(values ...*pmodel.TKline12H) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline12HDo) CreateInBatches(values []*pmodel.TKline12H, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline12HDo) Save(values ...*pmodel.TKline12H) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline12HDo) First() (*pmodel.TKline12H, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline12H), nil
	}
}

func (t tKline12HDo) Take() (*pmodel.TKline12H, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline12H), nil
	}
}

func (t tKline12HDo) Last() (*pmodel.TKline12H, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline12H), nil
	}
}

func (t tKline12HDo) Find() ([]*pmodel.TKline12H, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline12H), err
}

func (t tKline12HDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline12H, err error) {
	buf := make([]*pmodel.TKline12H, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline12HDo) FindInBatches(result *[]*pmodel.TKline12H, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline12HDo) Attrs(attrs ...field.AssignExpr) ITKline12HDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline12HDo) Assign(attrs ...field.AssignExpr) ITKline12HDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline12HDo) Joins(fields ...field.RelationField) ITKline12HDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline12HDo) Preload(fields ...field.RelationField) ITKline12HDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline12HDo) FirstOrInit() (*pmodel.TKline12H, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline12H), nil
	}
}

func (t tKline12HDo) FirstOrCreate() (*pmodel.TKline12H, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline12H), nil
	}
}

func (t tKline12HDo) FindByPage(offset int, limit int) (result []*pmodel.TKline12H, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline12HDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline12HDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline12HDo) Delete(models ...*pmodel.TKline12H) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline12HDo) withDO(do gen.Dao) *tKline12HDo {
	t.DO = *do.(*gen.DO)
	return t
}
