// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline1W(db *gorm.DB, opts ...gen.DOOption) tKline1W {
	_tKline1W := tKline1W{}

	_tKline1W.tKline1WDo.UseDB(db, opts...)
	_tKline1W.tKline1WDo.UseModel(&pmodel.TKline1W{})

	tableName := _tKline1W.tKline1WDo.TableName()
	_tKline1W.ALL = field.NewAsterisk(tableName)
	_tKline1W.Ts = field.NewTime(tableName, "ts")
	_tKline1W.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline1W.Open = field.NewFloat64(tableName, "open")
	_tKline1W.High = field.NewFloat64(tableName, "high")
	_tKline1W.Low = field.NewFloat64(tableName, "low")
	_tKline1W.Close = field.NewFloat64(tableName, "close")
	_tKline1W.Volume0 = field.NewFloat64(tableName, "volume0")
	_tKline1W.Volume1 = field.NewFloat64(tableName, "volume1")
	_tKline1W.Volume = field.NewFloat64(tableName, "volume")

	_tKline1W.fillFieldMap()

	return _tKline1W
}

type tKline1W struct {
	tKline1WDo tKline1WDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Open    field.Float64
	High    field.Float64
	Low     field.Float64
	Close   field.Float64
	Volume0 field.Float64
	Volume1 field.Float64
	Volume  field.Float64

	fieldMap map[string]field.Expr
}

func (t tKline1W) Table(newTableName string) *tKline1W {
	t.tKline1WDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline1W) As(alias string) *tKline1W {
	t.tKline1WDo.DO = *(t.tKline1WDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline1W) updateTableName(table string) *tKline1W {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Open = field.NewFloat64(table, "open")
	t.High = field.NewFloat64(table, "high")
	t.Low = field.NewFloat64(table, "low")
	t.Close = field.NewFloat64(table, "close")
	t.Volume0 = field.NewFloat64(table, "volume0")
	t.Volume1 = field.NewFloat64(table, "volume1")
	t.Volume = field.NewFloat64(table, "volume")

	t.fillFieldMap()

	return t
}

func (t *tKline1W) WithContext(ctx context.Context) ITKline1WDo { return t.tKline1WDo.WithContext(ctx) }

func (t tKline1W) TableName() string { return t.tKline1WDo.TableName() }

func (t tKline1W) Alias() string { return t.tKline1WDo.Alias() }

func (t tKline1W) Columns(cols ...field.Expr) gen.Columns { return t.tKline1WDo.Columns(cols...) }

func (t *tKline1W) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline1W) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["open"] = t.Open
	t.fieldMap["high"] = t.High
	t.fieldMap["low"] = t.Low
	t.fieldMap["close"] = t.Close
	t.fieldMap["volume0"] = t.Volume0
	t.fieldMap["volume1"] = t.Volume1
	t.fieldMap["volume"] = t.Volume
}

func (t tKline1W) clone(db *gorm.DB) tKline1W {
	t.tKline1WDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline1W) replaceDB(db *gorm.DB) tKline1W {
	t.tKline1WDo.ReplaceDB(db)
	return t
}

type tKline1WDo struct{ gen.DO }

type ITKline1WDo interface {
	gen.SubQuery
	Debug() ITKline1WDo
	WithContext(ctx context.Context) ITKline1WDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline1WDo
	WriteDB() ITKline1WDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline1WDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline1WDo
	Not(conds ...gen.Condition) ITKline1WDo
	Or(conds ...gen.Condition) ITKline1WDo
	Select(conds ...field.Expr) ITKline1WDo
	Where(conds ...gen.Condition) ITKline1WDo
	Order(conds ...field.Expr) ITKline1WDo
	Distinct(cols ...field.Expr) ITKline1WDo
	Omit(cols ...field.Expr) ITKline1WDo
	Join(table schema.Tabler, on ...field.Expr) ITKline1WDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1WDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline1WDo
	Group(cols ...field.Expr) ITKline1WDo
	Having(conds ...gen.Condition) ITKline1WDo
	Limit(limit int) ITKline1WDo
	Offset(offset int) ITKline1WDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1WDo
	Unscoped() ITKline1WDo
	Create(values ...*pmodel.TKline1W) error
	CreateInBatches(values []*pmodel.TKline1W, batchSize int) error
	Save(values ...*pmodel.TKline1W) error
	First() (*pmodel.TKline1W, error)
	Take() (*pmodel.TKline1W, error)
	Last() (*pmodel.TKline1W, error)
	Find() ([]*pmodel.TKline1W, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1W, err error)
	FindInBatches(result *[]*pmodel.TKline1W, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline1W) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline1WDo
	Assign(attrs ...field.AssignExpr) ITKline1WDo
	Joins(fields ...field.RelationField) ITKline1WDo
	Preload(fields ...field.RelationField) ITKline1WDo
	FirstOrInit() (*pmodel.TKline1W, error)
	FirstOrCreate() (*pmodel.TKline1W, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline1W, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline1WDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline1WDo) Debug() ITKline1WDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline1WDo) WithContext(ctx context.Context) ITKline1WDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline1WDo) ReadDB() ITKline1WDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline1WDo) WriteDB() ITKline1WDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline1WDo) Session(config *gorm.Session) ITKline1WDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline1WDo) Clauses(conds ...clause.Expression) ITKline1WDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline1WDo) Returning(value interface{}, columns ...string) ITKline1WDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline1WDo) Not(conds ...gen.Condition) ITKline1WDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline1WDo) Or(conds ...gen.Condition) ITKline1WDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline1WDo) Select(conds ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline1WDo) Where(conds ...gen.Condition) ITKline1WDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline1WDo) Order(conds ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline1WDo) Distinct(cols ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline1WDo) Omit(cols ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline1WDo) Join(table schema.Tabler, on ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline1WDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline1WDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline1WDo) Group(cols ...field.Expr) ITKline1WDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline1WDo) Having(conds ...gen.Condition) ITKline1WDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline1WDo) Limit(limit int) ITKline1WDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline1WDo) Offset(offset int) ITKline1WDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline1WDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1WDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline1WDo) Unscoped() ITKline1WDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline1WDo) Create(values ...*pmodel.TKline1W) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline1WDo) CreateInBatches(values []*pmodel.TKline1W, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline1WDo) Save(values ...*pmodel.TKline1W) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline1WDo) First() (*pmodel.TKline1W, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1W), nil
	}
}

func (t tKline1WDo) Take() (*pmodel.TKline1W, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1W), nil
	}
}

func (t tKline1WDo) Last() (*pmodel.TKline1W, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1W), nil
	}
}

func (t tKline1WDo) Find() ([]*pmodel.TKline1W, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline1W), err
}

func (t tKline1WDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1W, err error) {
	buf := make([]*pmodel.TKline1W, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline1WDo) FindInBatches(result *[]*pmodel.TKline1W, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline1WDo) Attrs(attrs ...field.AssignExpr) ITKline1WDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline1WDo) Assign(attrs ...field.AssignExpr) ITKline1WDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline1WDo) Joins(fields ...field.RelationField) ITKline1WDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline1WDo) Preload(fields ...field.RelationField) ITKline1WDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline1WDo) FirstOrInit() (*pmodel.TKline1W, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1W), nil
	}
}

func (t tKline1WDo) FirstOrCreate() (*pmodel.TKline1W, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1W), nil
	}
}

func (t tKline1WDo) FindByPage(offset int, limit int) (result []*pmodel.TKline1W, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline1WDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline1WDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline1WDo) Delete(models ...*pmodel.TKline1W) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline1WDo) withDO(do gen.Dao) *tKline1WDo {
	t.DO = *do.(*gen.DO)
	return t
}
