// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline1H(db *gorm.DB, opts ...gen.DOOption) tKline1H {
	_tKline1H := tKline1H{}

	_tKline1H.tKline1HDo.UseDB(db, opts...)
	_tKline1H.tKline1HDo.UseModel(&pmodel.TKline1H{})

	tableName := _tKline1H.tKline1HDo.TableName()
	_tKline1H.ALL = field.NewAsterisk(tableName)
	_tKline1H.Ts = field.NewTime(tableName, "ts")
	_tKline1H.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline1H.Open = field.NewFloat64(tableName, "open")
	_tKline1H.High = field.NewFloat64(tableName, "high")
	_tKline1H.Low = field.NewFloat64(tableName, "low")
	_tKline1H.Close = field.NewFloat64(tableName, "close")
	_tKline1H.Volume0 = field.NewFloat64(tableName, "volume0")
	_tKline1H.Volume1 = field.NewFloat64(tableName, "volume1")
	_tKline1H.Volume = field.NewFloat64(tableName, "volume")

	_tKline1H.fillFieldMap()

	return _tKline1H
}

type tKline1H struct {
	tKline1HDo tKline1HDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Open    field.Float64
	High    field.Float64
	Low     field.Float64
	Close   field.Float64
	Volume0 field.Float64
	Volume1 field.Float64
	Volume  field.Float64

	fieldMap map[string]field.Expr
}

func (t tKline1H) Table(newTableName string) *tKline1H {
	t.tKline1HDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline1H) As(alias string) *tKline1H {
	t.tKline1HDo.DO = *(t.tKline1HDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline1H) updateTableName(table string) *tKline1H {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Open = field.NewFloat64(table, "open")
	t.High = field.NewFloat64(table, "high")
	t.Low = field.NewFloat64(table, "low")
	t.Close = field.NewFloat64(table, "close")
	t.Volume0 = field.NewFloat64(table, "volume0")
	t.Volume1 = field.NewFloat64(table, "volume1")
	t.Volume = field.NewFloat64(table, "volume")

	t.fillFieldMap()

	return t
}

func (t *tKline1H) WithContext(ctx context.Context) ITKline1HDo { return t.tKline1HDo.WithContext(ctx) }

func (t tKline1H) TableName() string { return t.tKline1HDo.TableName() }

func (t tKline1H) Alias() string { return t.tKline1HDo.Alias() }

func (t tKline1H) Columns(cols ...field.Expr) gen.Columns { return t.tKline1HDo.Columns(cols...) }

func (t *tKline1H) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline1H) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["open"] = t.Open
	t.fieldMap["high"] = t.High
	t.fieldMap["low"] = t.Low
	t.fieldMap["close"] = t.Close
	t.fieldMap["volume0"] = t.Volume0
	t.fieldMap["volume1"] = t.Volume1
	t.fieldMap["volume"] = t.Volume
}

func (t tKline1H) clone(db *gorm.DB) tKline1H {
	t.tKline1HDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline1H) replaceDB(db *gorm.DB) tKline1H {
	t.tKline1HDo.ReplaceDB(db)
	return t
}

type tKline1HDo struct{ gen.DO }

type ITKline1HDo interface {
	gen.SubQuery
	Debug() ITKline1HDo
	WithContext(ctx context.Context) ITKline1HDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline1HDo
	WriteDB() ITKline1HDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline1HDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline1HDo
	Not(conds ...gen.Condition) ITKline1HDo
	Or(conds ...gen.Condition) ITKline1HDo
	Select(conds ...field.Expr) ITKline1HDo
	Where(conds ...gen.Condition) ITKline1HDo
	Order(conds ...field.Expr) ITKline1HDo
	Distinct(cols ...field.Expr) ITKline1HDo
	Omit(cols ...field.Expr) ITKline1HDo
	Join(table schema.Tabler, on ...field.Expr) ITKline1HDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1HDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline1HDo
	Group(cols ...field.Expr) ITKline1HDo
	Having(conds ...gen.Condition) ITKline1HDo
	Limit(limit int) ITKline1HDo
	Offset(offset int) ITKline1HDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1HDo
	Unscoped() ITKline1HDo
	Create(values ...*pmodel.TKline1H) error
	CreateInBatches(values []*pmodel.TKline1H, batchSize int) error
	Save(values ...*pmodel.TKline1H) error
	First() (*pmodel.TKline1H, error)
	Take() (*pmodel.TKline1H, error)
	Last() (*pmodel.TKline1H, error)
	Find() ([]*pmodel.TKline1H, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1H, err error)
	FindInBatches(result *[]*pmodel.TKline1H, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline1H) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline1HDo
	Assign(attrs ...field.AssignExpr) ITKline1HDo
	Joins(fields ...field.RelationField) ITKline1HDo
	Preload(fields ...field.RelationField) ITKline1HDo
	FirstOrInit() (*pmodel.TKline1H, error)
	FirstOrCreate() (*pmodel.TKline1H, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline1H, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline1HDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline1HDo) Debug() ITKline1HDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline1HDo) WithContext(ctx context.Context) ITKline1HDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline1HDo) ReadDB() ITKline1HDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline1HDo) WriteDB() ITKline1HDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline1HDo) Session(config *gorm.Session) ITKline1HDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline1HDo) Clauses(conds ...clause.Expression) ITKline1HDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline1HDo) Returning(value interface{}, columns ...string) ITKline1HDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline1HDo) Not(conds ...gen.Condition) ITKline1HDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline1HDo) Or(conds ...gen.Condition) ITKline1HDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline1HDo) Select(conds ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline1HDo) Where(conds ...gen.Condition) ITKline1HDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline1HDo) Order(conds ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline1HDo) Distinct(cols ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline1HDo) Omit(cols ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline1HDo) Join(table schema.Tabler, on ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline1HDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline1HDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline1HDo) Group(cols ...field.Expr) ITKline1HDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline1HDo) Having(conds ...gen.Condition) ITKline1HDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline1HDo) Limit(limit int) ITKline1HDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline1HDo) Offset(offset int) ITKline1HDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline1HDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline1HDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline1HDo) Unscoped() ITKline1HDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline1HDo) Create(values ...*pmodel.TKline1H) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline1HDo) CreateInBatches(values []*pmodel.TKline1H, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline1HDo) Save(values ...*pmodel.TKline1H) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline1HDo) First() (*pmodel.TKline1H, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1H), nil
	}
}

func (t tKline1HDo) Take() (*pmodel.TKline1H, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1H), nil
	}
}

func (t tKline1HDo) Last() (*pmodel.TKline1H, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1H), nil
	}
}

func (t tKline1HDo) Find() ([]*pmodel.TKline1H, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline1H), err
}

func (t tKline1HDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline1H, err error) {
	buf := make([]*pmodel.TKline1H, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline1HDo) FindInBatches(result *[]*pmodel.TKline1H, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline1HDo) Attrs(attrs ...field.AssignExpr) ITKline1HDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline1HDo) Assign(attrs ...field.AssignExpr) ITKline1HDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline1HDo) Joins(fields ...field.RelationField) ITKline1HDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline1HDo) Preload(fields ...field.RelationField) ITKline1HDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline1HDo) FirstOrInit() (*pmodel.TKline1H, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1H), nil
	}
}

func (t tKline1HDo) FirstOrCreate() (*pmodel.TKline1H, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline1H), nil
	}
}

func (t tKline1HDo) FindByPage(offset int, limit int) (result []*pmodel.TKline1H, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline1HDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline1HDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline1HDo) Delete(models ...*pmodel.TKline1H) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline1HDo) withDO(do gen.Dao) *tKline1HDo {
	t.DO = *do.(*gen.DO)
	return t
}
