// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dexerlab/utils-go/dal/pmodel"
)

func newTKline15M(db *gorm.DB, opts ...gen.DOOption) tKline15M {
	_tKline15M := tKline15M{}

	_tKline15M.tKline15MDo.UseDB(db, opts...)
	_tKline15M.tKline15MDo.UseModel(&pmodel.TKline15M{})

	tableName := _tKline15M.tKline15MDo.TableName()
	_tKline15M.ALL = field.NewAsterisk(tableName)
	_tKline15M.Ts = field.NewTime(tableName, "ts")
	_tKline15M.PoolID = field.NewInt64(tableName, "pool_id")
	_tKline15M.Open = field.NewFloat64(tableName, "open")
	_tKline15M.High = field.NewFloat64(tableName, "high")
	_tKline15M.Low = field.NewFloat64(tableName, "low")
	_tKline15M.Close = field.NewFloat64(tableName, "close")
	_tKline15M.Volume0 = field.NewFloat64(tableName, "volume0")
	_tKline15M.Volume1 = field.NewFloat64(tableName, "volume1")
	_tKline15M.Volume = field.NewFloat64(tableName, "volume")

	_tKline15M.fillFieldMap()

	return _tKline15M
}

type tKline15M struct {
	tKline15MDo tKline15MDo

	ALL     field.Asterisk
	Ts      field.Time
	PoolID  field.Int64
	Open    field.Float64
	High    field.Float64
	Low     field.Float64
	Close   field.Float64
	Volume0 field.Float64
	Volume1 field.Float64
	Volume  field.Float64

	fieldMap map[string]field.Expr
}

func (t tKline15M) Table(newTableName string) *tKline15M {
	t.tKline15MDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKline15M) As(alias string) *tKline15M {
	t.tKline15MDo.DO = *(t.tKline15MDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKline15M) updateTableName(table string) *tKline15M {
	t.ALL = field.NewAsterisk(table)
	t.Ts = field.NewTime(table, "ts")
	t.PoolID = field.NewInt64(table, "pool_id")
	t.Open = field.NewFloat64(table, "open")
	t.High = field.NewFloat64(table, "high")
	t.Low = field.NewFloat64(table, "low")
	t.Close = field.NewFloat64(table, "close")
	t.Volume0 = field.NewFloat64(table, "volume0")
	t.Volume1 = field.NewFloat64(table, "volume1")
	t.Volume = field.NewFloat64(table, "volume")

	t.fillFieldMap()

	return t
}

func (t *tKline15M) WithContext(ctx context.Context) ITKline15MDo {
	return t.tKline15MDo.WithContext(ctx)
}

func (t tKline15M) TableName() string { return t.tKline15MDo.TableName() }

func (t tKline15M) Alias() string { return t.tKline15MDo.Alias() }

func (t tKline15M) Columns(cols ...field.Expr) gen.Columns { return t.tKline15MDo.Columns(cols...) }

func (t *tKline15M) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKline15M) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["ts"] = t.Ts
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["open"] = t.Open
	t.fieldMap["high"] = t.High
	t.fieldMap["low"] = t.Low
	t.fieldMap["close"] = t.Close
	t.fieldMap["volume0"] = t.Volume0
	t.fieldMap["volume1"] = t.Volume1
	t.fieldMap["volume"] = t.Volume
}

func (t tKline15M) clone(db *gorm.DB) tKline15M {
	t.tKline15MDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKline15M) replaceDB(db *gorm.DB) tKline15M {
	t.tKline15MDo.ReplaceDB(db)
	return t
}

type tKline15MDo struct{ gen.DO }

type ITKline15MDo interface {
	gen.SubQuery
	Debug() ITKline15MDo
	WithContext(ctx context.Context) ITKline15MDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKline15MDo
	WriteDB() ITKline15MDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKline15MDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKline15MDo
	Not(conds ...gen.Condition) ITKline15MDo
	Or(conds ...gen.Condition) ITKline15MDo
	Select(conds ...field.Expr) ITKline15MDo
	Where(conds ...gen.Condition) ITKline15MDo
	Order(conds ...field.Expr) ITKline15MDo
	Distinct(cols ...field.Expr) ITKline15MDo
	Omit(cols ...field.Expr) ITKline15MDo
	Join(table schema.Tabler, on ...field.Expr) ITKline15MDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKline15MDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKline15MDo
	Group(cols ...field.Expr) ITKline15MDo
	Having(conds ...gen.Condition) ITKline15MDo
	Limit(limit int) ITKline15MDo
	Offset(offset int) ITKline15MDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline15MDo
	Unscoped() ITKline15MDo
	Create(values ...*pmodel.TKline15M) error
	CreateInBatches(values []*pmodel.TKline15M, batchSize int) error
	Save(values ...*pmodel.TKline15M) error
	First() (*pmodel.TKline15M, error)
	Take() (*pmodel.TKline15M, error)
	Last() (*pmodel.TKline15M, error)
	Find() ([]*pmodel.TKline15M, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline15M, err error)
	FindInBatches(result *[]*pmodel.TKline15M, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pmodel.TKline15M) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKline15MDo
	Assign(attrs ...field.AssignExpr) ITKline15MDo
	Joins(fields ...field.RelationField) ITKline15MDo
	Preload(fields ...field.RelationField) ITKline15MDo
	FirstOrInit() (*pmodel.TKline15M, error)
	FirstOrCreate() (*pmodel.TKline15M, error)
	FindByPage(offset int, limit int) (result []*pmodel.TKline15M, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKline15MDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKline15MDo) Debug() ITKline15MDo {
	return t.withDO(t.DO.Debug())
}

func (t tKline15MDo) WithContext(ctx context.Context) ITKline15MDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKline15MDo) ReadDB() ITKline15MDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKline15MDo) WriteDB() ITKline15MDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKline15MDo) Session(config *gorm.Session) ITKline15MDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKline15MDo) Clauses(conds ...clause.Expression) ITKline15MDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKline15MDo) Returning(value interface{}, columns ...string) ITKline15MDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKline15MDo) Not(conds ...gen.Condition) ITKline15MDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKline15MDo) Or(conds ...gen.Condition) ITKline15MDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKline15MDo) Select(conds ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKline15MDo) Where(conds ...gen.Condition) ITKline15MDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKline15MDo) Order(conds ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKline15MDo) Distinct(cols ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKline15MDo) Omit(cols ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKline15MDo) Join(table schema.Tabler, on ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKline15MDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKline15MDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKline15MDo) Group(cols ...field.Expr) ITKline15MDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKline15MDo) Having(conds ...gen.Condition) ITKline15MDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKline15MDo) Limit(limit int) ITKline15MDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKline15MDo) Offset(offset int) ITKline15MDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKline15MDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKline15MDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKline15MDo) Unscoped() ITKline15MDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKline15MDo) Create(values ...*pmodel.TKline15M) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKline15MDo) CreateInBatches(values []*pmodel.TKline15M, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKline15MDo) Save(values ...*pmodel.TKline15M) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKline15MDo) First() (*pmodel.TKline15M, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline15M), nil
	}
}

func (t tKline15MDo) Take() (*pmodel.TKline15M, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline15M), nil
	}
}

func (t tKline15MDo) Last() (*pmodel.TKline15M, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline15M), nil
	}
}

func (t tKline15MDo) Find() ([]*pmodel.TKline15M, error) {
	result, err := t.DO.Find()
	return result.([]*pmodel.TKline15M), err
}

func (t tKline15MDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pmodel.TKline15M, err error) {
	buf := make([]*pmodel.TKline15M, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKline15MDo) FindInBatches(result *[]*pmodel.TKline15M, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKline15MDo) Attrs(attrs ...field.AssignExpr) ITKline15MDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKline15MDo) Assign(attrs ...field.AssignExpr) ITKline15MDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKline15MDo) Joins(fields ...field.RelationField) ITKline15MDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKline15MDo) Preload(fields ...field.RelationField) ITKline15MDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKline15MDo) FirstOrInit() (*pmodel.TKline15M, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline15M), nil
	}
}

func (t tKline15MDo) FirstOrCreate() (*pmodel.TKline15M, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pmodel.TKline15M), nil
	}
}

func (t tKline15MDo) FindByPage(offset int, limit int) (result []*pmodel.TKline15M, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKline15MDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKline15MDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKline15MDo) Delete(models ...*pmodel.TKline15M) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKline15MDo) withDO(do gen.Dao) *tKline15MDo {
	t.DO = *do.(*gen.DO)
	return t
}
